// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PAppSession.proto

package com.argo.sdk.protobuf;

public interface PAppSessionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PAppSession)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string sessionId = 1;</code>
   */
  boolean hasSessionId();
  /**
   * <code>optional string sessionId = 1;</code>
   */
  java.lang.String getSessionId();
  /**
   * <code>optional string sessionId = 1;</code>
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();

  /**
   * <code>optional string realName = 2;</code>
   */
  boolean hasRealName();
  /**
   * <code>optional string realName = 2;</code>
   */
  java.lang.String getRealName();
  /**
   * <code>optional string realName = 2;</code>
   */
  com.google.protobuf.ByteString
      getRealNameBytes();

  /**
   * <code>optional string userName = 3;</code>
   */
  boolean hasUserName();
  /**
   * <code>optional string userName = 3;</code>
   */
  java.lang.String getUserName();
  /**
   * <code>optional string userName = 3;</code>
   */
  com.google.protobuf.ByteString
      getUserNameBytes();

  /**
   * <code>optional int64 userId = 4;</code>
   */
  boolean hasUserId();
  /**
   * <code>optional int64 userId = 4;</code>
   */
  long getUserId();

  /**
   * <code>optional string secret = 5;</code>
   */
  boolean hasSecret();
  /**
   * <code>optional string secret = 5;</code>
   */
  java.lang.String getSecret();
  /**
   * <code>optional string secret = 5;</code>
   */
  com.google.protobuf.ByteString
      getSecretBytes();

  /**
   * <code>optional string signinDate = 6;</code>
   */
  boolean hasSigninDate();
  /**
   * <code>optional string signinDate = 6;</code>
   */
  java.lang.String getSigninDate();
  /**
   * <code>optional string signinDate = 6;</code>
   */
  com.google.protobuf.ByteString
      getSigninDateBytes();

  /**
   * <code>optional string profileImageUrl = 7;</code>
   */
  boolean hasProfileImageUrl();
  /**
   * <code>optional string profileImageUrl = 7;</code>
   */
  java.lang.String getProfileImageUrl();
  /**
   * <code>optional string profileImageUrl = 7;</code>
   */
  com.google.protobuf.ByteString
      getProfileImageUrlBytes();

  /**
   * <code>optional string appName = 8;</code>
   */
  boolean hasAppName();
  /**
   * <code>optional string appName = 8;</code>
   */
  java.lang.String getAppName();
  /**
   * <code>optional string appName = 8;</code>
   */
  com.google.protobuf.ByteString
      getAppNameBytes();

  /**
   * <code>optional string deviceName = 9;</code>
   */
  boolean hasDeviceName();
  /**
   * <code>optional string deviceName = 9;</code>
   */
  java.lang.String getDeviceName();
  /**
   * <code>optional string deviceName = 9;</code>
   */
  com.google.protobuf.ByteString
      getDeviceNameBytes();

  /**
   * <code>optional string deviceScreenSize = 10;</code>
   */
  boolean hasDeviceScreenSize();
  /**
   * <code>optional string deviceScreenSize = 10;</code>
   */
  java.lang.String getDeviceScreenSize();
  /**
   * <code>optional string deviceScreenSize = 10;</code>
   */
  com.google.protobuf.ByteString
      getDeviceScreenSizeBytes();

  /**
   * <code>optional string osName = 11;</code>
   */
  boolean hasOsName();
  /**
   * <code>optional string osName = 11;</code>
   */
  java.lang.String getOsName();
  /**
   * <code>optional string osName = 11;</code>
   */
  com.google.protobuf.ByteString
      getOsNameBytes();

  /**
   * <code>optional string osVersion = 12;</code>
   */
  boolean hasOsVersion();
  /**
   * <code>optional string osVersion = 12;</code>
   */
  java.lang.String getOsVersion();
  /**
   * <code>optional string osVersion = 12;</code>
   */
  com.google.protobuf.ByteString
      getOsVersionBytes();

  /**
   * <code>optional string packageVersion = 13;</code>
   */
  boolean hasPackageVersion();
  /**
   * <code>optional string packageVersion = 13;</code>
   */
  java.lang.String getPackageVersion();
  /**
   * <code>optional string packageVersion = 13;</code>
   */
  com.google.protobuf.ByteString
      getPackageVersionBytes();

  /**
   * <code>optional string packageName = 14;</code>
   */
  boolean hasPackageName();
  /**
   * <code>optional string packageName = 14;</code>
   */
  java.lang.String getPackageName();
  /**
   * <code>optional string packageName = 14;</code>
   */
  com.google.protobuf.ByteString
      getPackageNameBytes();

  /**
   * <code>optional string deviceId = 15;</code>
   */
  boolean hasDeviceId();
  /**
   * <code>optional string deviceId = 15;</code>
   */
  java.lang.String getDeviceId();
  /**
   * <code>optional string deviceId = 15;</code>
   */
  com.google.protobuf.ByteString
      getDeviceIdBytes();

  /**
   * <code>optional string deviceToken = 16;</code>
   */
  boolean hasDeviceToken();
  /**
   * <code>optional string deviceToken = 16;</code>
   */
  java.lang.String getDeviceToken();
  /**
   * <code>optional string deviceToken = 16;</code>
   */
  com.google.protobuf.ByteString
      getDeviceTokenBytes();

  /**
   * <code>optional int32 apnsEnabled = 17;</code>
   */
  boolean hasApnsEnabled();
  /**
   * <code>optional int32 apnsEnabled = 17;</code>
   */
  int getApnsEnabled();

  /**
   * <code>optional string latesAppVers = 18;</code>
   */
  boolean hasLatesAppVers();
  /**
   * <code>optional string latesAppVers = 18;</code>
   */
  java.lang.String getLatesAppVers();
  /**
   * <code>optional string latesAppVers = 18;</code>
   */
  com.google.protobuf.ByteString
      getLatesAppVersBytes();

  /**
   * <code>optional string localeIdentifier = 19;</code>
   */
  boolean hasLocaleIdentifier();
  /**
   * <code>optional string localeIdentifier = 19;</code>
   */
  java.lang.String getLocaleIdentifier();
  /**
   * <code>optional string localeIdentifier = 19;</code>
   */
  com.google.protobuf.ByteString
      getLocaleIdentifierBytes();

  /**
   * <code>optional float latitude = 20;</code>
   */
  boolean hasLatitude();
  /**
   * <code>optional float latitude = 20;</code>
   */
  float getLatitude();

  /**
   * <code>optional float longitude = 21;</code>
   */
  boolean hasLongitude();
  /**
   * <code>optional float longitude = 21;</code>
   */
  float getLongitude();

  /**
   * <code>optional int32 cityId = 22;</code>
   */
  boolean hasCityId();
  /**
   * <code>optional int32 cityId = 22;</code>
   */
  int getCityId();

  /**
   * <code>optional int32 userKind = 23;</code>
   */
  boolean hasUserKind();
  /**
   * <code>optional int32 userKind = 23;</code>
   */
  int getUserKind();

  /**
   * <code>optional int32 userDemo = 24;</code>
   */
  boolean hasUserDemo();
  /**
   * <code>optional int32 userDemo = 24;</code>
   */
  int getUserDemo();
}
