// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PAppRequest.proto

package com.argo.sdk.protobuf;

/**
 * Protobuf type {@code PAppRequest}
 */
public  final class PAppRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:PAppRequest)
    PAppRequestOrBuilder {
  // Use PAppRequest.newBuilder() to construct.
  private PAppRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PAppRequest() {
    authId_ = "";
    sessionId_ = "";
    version_ = 0;
    sign_ = "";
    nonce_ = "";
    userAgent_ = "";
    path_ = "";
    param_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PAppRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000001;
            authId_ = bs;
            break;
          }
          case 18: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000002;
            sessionId_ = bs;
            break;
          }
          case 24: {
            bitField0_ |= 0x00000004;
            version_ = input.readInt32();
            break;
          }
          case 34: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000008;
            sign_ = bs;
            break;
          }
          case 42: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000010;
            nonce_ = bs;
            break;
          }
          case 50: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000020;
            userAgent_ = bs;
            break;
          }
          case 58: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000040;
            path_ = bs;
            break;
          }
          case 66: {
            if (!((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
              param_ = new java.util.ArrayList<com.argo.sdk.protobuf.PAppRequestParam>();
              mutable_bitField0_ |= 0x00000080;
            }
            param_.add(
                input.readMessage(com.argo.sdk.protobuf.PAppRequestParam.PARSER, extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
        param_ = java.util.Collections.unmodifiableList(param_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.argo.sdk.protobuf.PAppRequestProto.internal_static_PAppRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.argo.sdk.protobuf.PAppRequestProto.internal_static_PAppRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.argo.sdk.protobuf.PAppRequest.class, com.argo.sdk.protobuf.PAppRequest.Builder.class);
  }

  private int bitField0_;
  public static final int AUTHID_FIELD_NUMBER = 1;
  private volatile java.lang.Object authId_;
  /**
   * <code>required string authId = 1;</code>
   */
  public boolean hasAuthId() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required string authId = 1;</code>
   */
  public java.lang.String getAuthId() {
    java.lang.Object ref = authId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        authId_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string authId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getAuthIdBytes() {
    java.lang.Object ref = authId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      authId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SESSIONID_FIELD_NUMBER = 2;
  private volatile java.lang.Object sessionId_;
  /**
   * <code>optional string sessionId = 2;</code>
   */
  public boolean hasSessionId() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional string sessionId = 2;</code>
   */
  public java.lang.String getSessionId() {
    java.lang.Object ref = sessionId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        sessionId_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string sessionId = 2;</code>
   */
  public com.google.protobuf.ByteString
      getSessionIdBytes() {
    java.lang.Object ref = sessionId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sessionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VERSION_FIELD_NUMBER = 3;
  private int version_;
  /**
   * <code>optional int32 version = 3;</code>
   */
  public boolean hasVersion() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>optional int32 version = 3;</code>
   */
  public int getVersion() {
    return version_;
  }

  public static final int SIGN_FIELD_NUMBER = 4;
  private volatile java.lang.Object sign_;
  /**
   * <code>optional string sign = 4;</code>
   */
  public boolean hasSign() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <code>optional string sign = 4;</code>
   */
  public java.lang.String getSign() {
    java.lang.Object ref = sign_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        sign_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string sign = 4;</code>
   */
  public com.google.protobuf.ByteString
      getSignBytes() {
    java.lang.Object ref = sign_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sign_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NONCE_FIELD_NUMBER = 5;
  private volatile java.lang.Object nonce_;
  /**
   * <code>optional string nonce = 5;</code>
   */
  public boolean hasNonce() {
    return ((bitField0_ & 0x00000010) == 0x00000010);
  }
  /**
   * <code>optional string nonce = 5;</code>
   */
  public java.lang.String getNonce() {
    java.lang.Object ref = nonce_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        nonce_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string nonce = 5;</code>
   */
  public com.google.protobuf.ByteString
      getNonceBytes() {
    java.lang.Object ref = nonce_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nonce_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USERAGENT_FIELD_NUMBER = 6;
  private volatile java.lang.Object userAgent_;
  /**
   * <code>optional string userAgent = 6;</code>
   */
  public boolean hasUserAgent() {
    return ((bitField0_ & 0x00000020) == 0x00000020);
  }
  /**
   * <code>optional string userAgent = 6;</code>
   */
  public java.lang.String getUserAgent() {
    java.lang.Object ref = userAgent_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        userAgent_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string userAgent = 6;</code>
   */
  public com.google.protobuf.ByteString
      getUserAgentBytes() {
    java.lang.Object ref = userAgent_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userAgent_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PATH_FIELD_NUMBER = 7;
  private volatile java.lang.Object path_;
  /**
   * <code>optional string path = 7;</code>
   */
  public boolean hasPath() {
    return ((bitField0_ & 0x00000040) == 0x00000040);
  }
  /**
   * <code>optional string path = 7;</code>
   */
  public java.lang.String getPath() {
    java.lang.Object ref = path_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        path_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string path = 7;</code>
   */
  public com.google.protobuf.ByteString
      getPathBytes() {
    java.lang.Object ref = path_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      path_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PARAM_FIELD_NUMBER = 8;
  private java.util.List<com.argo.sdk.protobuf.PAppRequestParam> param_;
  /**
   * <code>repeated .PAppRequestParam param = 8;</code>
   */
  public java.util.List<com.argo.sdk.protobuf.PAppRequestParam> getParamList() {
    return param_;
  }
  /**
   * <code>repeated .PAppRequestParam param = 8;</code>
   */
  public java.util.List<? extends com.argo.sdk.protobuf.PAppRequestParamOrBuilder> 
      getParamOrBuilderList() {
    return param_;
  }
  /**
   * <code>repeated .PAppRequestParam param = 8;</code>
   */
  public int getParamCount() {
    return param_.size();
  }
  /**
   * <code>repeated .PAppRequestParam param = 8;</code>
   */
  public com.argo.sdk.protobuf.PAppRequestParam getParam(int index) {
    return param_.get(index);
  }
  /**
   * <code>repeated .PAppRequestParam param = 8;</code>
   */
  public com.argo.sdk.protobuf.PAppRequestParamOrBuilder getParamOrBuilder(
      int index) {
    return param_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasAuthId()) {
      memoizedIsInitialized = 0;
      return false;
    }
    for (int i = 0; i < getParamCount(); i++) {
      if (!getParam(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, authId_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, sessionId_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeInt32(3, version_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, sign_);
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, nonce_);
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, userAgent_);
    }
    if (((bitField0_ & 0x00000040) == 0x00000040)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, path_);
    }
    for (int i = 0; i < param_.size(); i++) {
      output.writeMessage(8, param_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, authId_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, sessionId_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, version_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, sign_);
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, nonce_);
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, userAgent_);
    }
    if (((bitField0_ & 0x00000040) == 0x00000040)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, path_);
    }
    for (int i = 0; i < param_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, param_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.argo.sdk.protobuf.PAppRequest)) {
      return super.equals(obj);
    }
    com.argo.sdk.protobuf.PAppRequest other = (com.argo.sdk.protobuf.PAppRequest) obj;

    boolean result = true;
    result = result && (hasAuthId() == other.hasAuthId());
    if (hasAuthId()) {
      result = result && getAuthId()
          .equals(other.getAuthId());
    }
    result = result && (hasSessionId() == other.hasSessionId());
    if (hasSessionId()) {
      result = result && getSessionId()
          .equals(other.getSessionId());
    }
    result = result && (hasVersion() == other.hasVersion());
    if (hasVersion()) {
      result = result && (getVersion()
          == other.getVersion());
    }
    result = result && (hasSign() == other.hasSign());
    if (hasSign()) {
      result = result && getSign()
          .equals(other.getSign());
    }
    result = result && (hasNonce() == other.hasNonce());
    if (hasNonce()) {
      result = result && getNonce()
          .equals(other.getNonce());
    }
    result = result && (hasUserAgent() == other.hasUserAgent());
    if (hasUserAgent()) {
      result = result && getUserAgent()
          .equals(other.getUserAgent());
    }
    result = result && (hasPath() == other.hasPath());
    if (hasPath()) {
      result = result && getPath()
          .equals(other.getPath());
    }
    result = result && getParamList()
        .equals(other.getParamList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (hasAuthId()) {
      hash = (37 * hash) + AUTHID_FIELD_NUMBER;
      hash = (53 * hash) + getAuthId().hashCode();
    }
    if (hasSessionId()) {
      hash = (37 * hash) + SESSIONID_FIELD_NUMBER;
      hash = (53 * hash) + getSessionId().hashCode();
    }
    if (hasVersion()) {
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion();
    }
    if (hasSign()) {
      hash = (37 * hash) + SIGN_FIELD_NUMBER;
      hash = (53 * hash) + getSign().hashCode();
    }
    if (hasNonce()) {
      hash = (37 * hash) + NONCE_FIELD_NUMBER;
      hash = (53 * hash) + getNonce().hashCode();
    }
    if (hasUserAgent()) {
      hash = (37 * hash) + USERAGENT_FIELD_NUMBER;
      hash = (53 * hash) + getUserAgent().hashCode();
    }
    if (hasPath()) {
      hash = (37 * hash) + PATH_FIELD_NUMBER;
      hash = (53 * hash) + getPath().hashCode();
    }
    if (getParamCount() > 0) {
      hash = (37 * hash) + PARAM_FIELD_NUMBER;
      hash = (53 * hash) + getParamList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.argo.sdk.protobuf.PAppRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.argo.sdk.protobuf.PAppRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.argo.sdk.protobuf.PAppRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.argo.sdk.protobuf.PAppRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.argo.sdk.protobuf.PAppRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.argo.sdk.protobuf.PAppRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.argo.sdk.protobuf.PAppRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.argo.sdk.protobuf.PAppRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.argo.sdk.protobuf.PAppRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.argo.sdk.protobuf.PAppRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.argo.sdk.protobuf.PAppRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code PAppRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PAppRequest)
      com.argo.sdk.protobuf.PAppRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.argo.sdk.protobuf.PAppRequestProto.internal_static_PAppRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.argo.sdk.protobuf.PAppRequestProto.internal_static_PAppRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.argo.sdk.protobuf.PAppRequest.class, com.argo.sdk.protobuf.PAppRequest.Builder.class);
    }

    // Construct using com.argo.sdk.protobuf.PAppRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getParamFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      authId_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      sessionId_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      version_ = 0;
      bitField0_ = (bitField0_ & ~0x00000004);
      sign_ = "";
      bitField0_ = (bitField0_ & ~0x00000008);
      nonce_ = "";
      bitField0_ = (bitField0_ & ~0x00000010);
      userAgent_ = "";
      bitField0_ = (bitField0_ & ~0x00000020);
      path_ = "";
      bitField0_ = (bitField0_ & ~0x00000040);
      if (paramBuilder_ == null) {
        param_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000080);
      } else {
        paramBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.argo.sdk.protobuf.PAppRequestProto.internal_static_PAppRequest_descriptor;
    }

    public com.argo.sdk.protobuf.PAppRequest getDefaultInstanceForType() {
      return com.argo.sdk.protobuf.PAppRequest.getDefaultInstance();
    }

    public com.argo.sdk.protobuf.PAppRequest build() {
      com.argo.sdk.protobuf.PAppRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.argo.sdk.protobuf.PAppRequest buildPartial() {
      com.argo.sdk.protobuf.PAppRequest result = new com.argo.sdk.protobuf.PAppRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.authId_ = authId_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.sessionId_ = sessionId_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.version_ = version_;
      if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
        to_bitField0_ |= 0x00000008;
      }
      result.sign_ = sign_;
      if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
        to_bitField0_ |= 0x00000010;
      }
      result.nonce_ = nonce_;
      if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
        to_bitField0_ |= 0x00000020;
      }
      result.userAgent_ = userAgent_;
      if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
        to_bitField0_ |= 0x00000040;
      }
      result.path_ = path_;
      if (paramBuilder_ == null) {
        if (((bitField0_ & 0x00000080) == 0x00000080)) {
          param_ = java.util.Collections.unmodifiableList(param_);
          bitField0_ = (bitField0_ & ~0x00000080);
        }
        result.param_ = param_;
      } else {
        result.param_ = paramBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.argo.sdk.protobuf.PAppRequest) {
        return mergeFrom((com.argo.sdk.protobuf.PAppRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.argo.sdk.protobuf.PAppRequest other) {
      if (other == com.argo.sdk.protobuf.PAppRequest.getDefaultInstance()) return this;
      if (other.hasAuthId()) {
        bitField0_ |= 0x00000001;
        authId_ = other.authId_;
        onChanged();
      }
      if (other.hasSessionId()) {
        bitField0_ |= 0x00000002;
        sessionId_ = other.sessionId_;
        onChanged();
      }
      if (other.hasVersion()) {
        setVersion(other.getVersion());
      }
      if (other.hasSign()) {
        bitField0_ |= 0x00000008;
        sign_ = other.sign_;
        onChanged();
      }
      if (other.hasNonce()) {
        bitField0_ |= 0x00000010;
        nonce_ = other.nonce_;
        onChanged();
      }
      if (other.hasUserAgent()) {
        bitField0_ |= 0x00000020;
        userAgent_ = other.userAgent_;
        onChanged();
      }
      if (other.hasPath()) {
        bitField0_ |= 0x00000040;
        path_ = other.path_;
        onChanged();
      }
      if (paramBuilder_ == null) {
        if (!other.param_.isEmpty()) {
          if (param_.isEmpty()) {
            param_ = other.param_;
            bitField0_ = (bitField0_ & ~0x00000080);
          } else {
            ensureParamIsMutable();
            param_.addAll(other.param_);
          }
          onChanged();
        }
      } else {
        if (!other.param_.isEmpty()) {
          if (paramBuilder_.isEmpty()) {
            paramBuilder_.dispose();
            paramBuilder_ = null;
            param_ = other.param_;
            bitField0_ = (bitField0_ & ~0x00000080);
            paramBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getParamFieldBuilder() : null;
          } else {
            paramBuilder_.addAllMessages(other.param_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      if (!hasAuthId()) {
        return false;
      }
      for (int i = 0; i < getParamCount(); i++) {
        if (!getParam(i).isInitialized()) {
          return false;
        }
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.argo.sdk.protobuf.PAppRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.argo.sdk.protobuf.PAppRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object authId_ = "";
    /**
     * <code>required string authId = 1;</code>
     */
    public boolean hasAuthId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string authId = 1;</code>
     */
    public java.lang.String getAuthId() {
      java.lang.Object ref = authId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          authId_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string authId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAuthIdBytes() {
      java.lang.Object ref = authId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        authId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string authId = 1;</code>
     */
    public Builder setAuthId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      authId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string authId = 1;</code>
     */
    public Builder clearAuthId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      authId_ = getDefaultInstance().getAuthId();
      onChanged();
      return this;
    }
    /**
     * <code>required string authId = 1;</code>
     */
    public Builder setAuthIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      authId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object sessionId_ = "";
    /**
     * <code>optional string sessionId = 2;</code>
     */
    public boolean hasSessionId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string sessionId = 2;</code>
     */
    public java.lang.String getSessionId() {
      java.lang.Object ref = sessionId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sessionId_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string sessionId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSessionIdBytes() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string sessionId = 2;</code>
     */
    public Builder setSessionId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      sessionId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string sessionId = 2;</code>
     */
    public Builder clearSessionId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      sessionId_ = getDefaultInstance().getSessionId();
      onChanged();
      return this;
    }
    /**
     * <code>optional string sessionId = 2;</code>
     */
    public Builder setSessionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      sessionId_ = value;
      onChanged();
      return this;
    }

    private int version_ ;
    /**
     * <code>optional int32 version = 3;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 version = 3;</code>
     */
    public int getVersion() {
      return version_;
    }
    /**
     * <code>optional int32 version = 3;</code>
     */
    public Builder setVersion(int value) {
      bitField0_ |= 0x00000004;
      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 version = 3;</code>
     */
    public Builder clearVersion() {
      bitField0_ = (bitField0_ & ~0x00000004);
      version_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object sign_ = "";
    /**
     * <code>optional string sign = 4;</code>
     */
    public boolean hasSign() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string sign = 4;</code>
     */
    public java.lang.String getSign() {
      java.lang.Object ref = sign_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sign_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string sign = 4;</code>
     */
    public com.google.protobuf.ByteString
        getSignBytes() {
      java.lang.Object ref = sign_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sign_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string sign = 4;</code>
     */
    public Builder setSign(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      sign_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string sign = 4;</code>
     */
    public Builder clearSign() {
      bitField0_ = (bitField0_ & ~0x00000008);
      sign_ = getDefaultInstance().getSign();
      onChanged();
      return this;
    }
    /**
     * <code>optional string sign = 4;</code>
     */
    public Builder setSignBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      sign_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object nonce_ = "";
    /**
     * <code>optional string nonce = 5;</code>
     */
    public boolean hasNonce() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string nonce = 5;</code>
     */
    public java.lang.String getNonce() {
      java.lang.Object ref = nonce_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          nonce_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string nonce = 5;</code>
     */
    public com.google.protobuf.ByteString
        getNonceBytes() {
      java.lang.Object ref = nonce_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nonce_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string nonce = 5;</code>
     */
    public Builder setNonce(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      nonce_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string nonce = 5;</code>
     */
    public Builder clearNonce() {
      bitField0_ = (bitField0_ & ~0x00000010);
      nonce_ = getDefaultInstance().getNonce();
      onChanged();
      return this;
    }
    /**
     * <code>optional string nonce = 5;</code>
     */
    public Builder setNonceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      nonce_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object userAgent_ = "";
    /**
     * <code>optional string userAgent = 6;</code>
     */
    public boolean hasUserAgent() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string userAgent = 6;</code>
     */
    public java.lang.String getUserAgent() {
      java.lang.Object ref = userAgent_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userAgent_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string userAgent = 6;</code>
     */
    public com.google.protobuf.ByteString
        getUserAgentBytes() {
      java.lang.Object ref = userAgent_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userAgent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string userAgent = 6;</code>
     */
    public Builder setUserAgent(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
      userAgent_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string userAgent = 6;</code>
     */
    public Builder clearUserAgent() {
      bitField0_ = (bitField0_ & ~0x00000020);
      userAgent_ = getDefaultInstance().getUserAgent();
      onChanged();
      return this;
    }
    /**
     * <code>optional string userAgent = 6;</code>
     */
    public Builder setUserAgentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
      userAgent_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object path_ = "";
    /**
     * <code>optional string path = 7;</code>
     */
    public boolean hasPath() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string path = 7;</code>
     */
    public java.lang.String getPath() {
      java.lang.Object ref = path_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          path_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string path = 7;</code>
     */
    public com.google.protobuf.ByteString
        getPathBytes() {
      java.lang.Object ref = path_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        path_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string path = 7;</code>
     */
    public Builder setPath(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
      path_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string path = 7;</code>
     */
    public Builder clearPath() {
      bitField0_ = (bitField0_ & ~0x00000040);
      path_ = getDefaultInstance().getPath();
      onChanged();
      return this;
    }
    /**
     * <code>optional string path = 7;</code>
     */
    public Builder setPathBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
      path_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.argo.sdk.protobuf.PAppRequestParam> param_ =
      java.util.Collections.emptyList();
    private void ensureParamIsMutable() {
      if (!((bitField0_ & 0x00000080) == 0x00000080)) {
        param_ = new java.util.ArrayList<com.argo.sdk.protobuf.PAppRequestParam>(param_);
        bitField0_ |= 0x00000080;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.argo.sdk.protobuf.PAppRequestParam, com.argo.sdk.protobuf.PAppRequestParam.Builder, com.argo.sdk.protobuf.PAppRequestParamOrBuilder> paramBuilder_;

    /**
     * <code>repeated .PAppRequestParam param = 8;</code>
     */
    public java.util.List<com.argo.sdk.protobuf.PAppRequestParam> getParamList() {
      if (paramBuilder_ == null) {
        return java.util.Collections.unmodifiableList(param_);
      } else {
        return paramBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .PAppRequestParam param = 8;</code>
     */
    public int getParamCount() {
      if (paramBuilder_ == null) {
        return param_.size();
      } else {
        return paramBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .PAppRequestParam param = 8;</code>
     */
    public com.argo.sdk.protobuf.PAppRequestParam getParam(int index) {
      if (paramBuilder_ == null) {
        return param_.get(index);
      } else {
        return paramBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .PAppRequestParam param = 8;</code>
     */
    public Builder setParam(
        int index, com.argo.sdk.protobuf.PAppRequestParam value) {
      if (paramBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureParamIsMutable();
        param_.set(index, value);
        onChanged();
      } else {
        paramBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .PAppRequestParam param = 8;</code>
     */
    public Builder setParam(
        int index, com.argo.sdk.protobuf.PAppRequestParam.Builder builderForValue) {
      if (paramBuilder_ == null) {
        ensureParamIsMutable();
        param_.set(index, builderForValue.build());
        onChanged();
      } else {
        paramBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PAppRequestParam param = 8;</code>
     */
    public Builder addParam(com.argo.sdk.protobuf.PAppRequestParam value) {
      if (paramBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureParamIsMutable();
        param_.add(value);
        onChanged();
      } else {
        paramBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .PAppRequestParam param = 8;</code>
     */
    public Builder addParam(
        int index, com.argo.sdk.protobuf.PAppRequestParam value) {
      if (paramBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureParamIsMutable();
        param_.add(index, value);
        onChanged();
      } else {
        paramBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .PAppRequestParam param = 8;</code>
     */
    public Builder addParam(
        com.argo.sdk.protobuf.PAppRequestParam.Builder builderForValue) {
      if (paramBuilder_ == null) {
        ensureParamIsMutable();
        param_.add(builderForValue.build());
        onChanged();
      } else {
        paramBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PAppRequestParam param = 8;</code>
     */
    public Builder addParam(
        int index, com.argo.sdk.protobuf.PAppRequestParam.Builder builderForValue) {
      if (paramBuilder_ == null) {
        ensureParamIsMutable();
        param_.add(index, builderForValue.build());
        onChanged();
      } else {
        paramBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PAppRequestParam param = 8;</code>
     */
    public Builder addAllParam(
        java.lang.Iterable<? extends com.argo.sdk.protobuf.PAppRequestParam> values) {
      if (paramBuilder_ == null) {
        ensureParamIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, param_);
        onChanged();
      } else {
        paramBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .PAppRequestParam param = 8;</code>
     */
    public Builder clearParam() {
      if (paramBuilder_ == null) {
        param_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
      } else {
        paramBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .PAppRequestParam param = 8;</code>
     */
    public Builder removeParam(int index) {
      if (paramBuilder_ == null) {
        ensureParamIsMutable();
        param_.remove(index);
        onChanged();
      } else {
        paramBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .PAppRequestParam param = 8;</code>
     */
    public com.argo.sdk.protobuf.PAppRequestParam.Builder getParamBuilder(
        int index) {
      return getParamFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .PAppRequestParam param = 8;</code>
     */
    public com.argo.sdk.protobuf.PAppRequestParamOrBuilder getParamOrBuilder(
        int index) {
      if (paramBuilder_ == null) {
        return param_.get(index);  } else {
        return paramBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .PAppRequestParam param = 8;</code>
     */
    public java.util.List<? extends com.argo.sdk.protobuf.PAppRequestParamOrBuilder> 
         getParamOrBuilderList() {
      if (paramBuilder_ != null) {
        return paramBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(param_);
      }
    }
    /**
     * <code>repeated .PAppRequestParam param = 8;</code>
     */
    public com.argo.sdk.protobuf.PAppRequestParam.Builder addParamBuilder() {
      return getParamFieldBuilder().addBuilder(
          com.argo.sdk.protobuf.PAppRequestParam.getDefaultInstance());
    }
    /**
     * <code>repeated .PAppRequestParam param = 8;</code>
     */
    public com.argo.sdk.protobuf.PAppRequestParam.Builder addParamBuilder(
        int index) {
      return getParamFieldBuilder().addBuilder(
          index, com.argo.sdk.protobuf.PAppRequestParam.getDefaultInstance());
    }
    /**
     * <code>repeated .PAppRequestParam param = 8;</code>
     */
    public java.util.List<com.argo.sdk.protobuf.PAppRequestParam.Builder> 
         getParamBuilderList() {
      return getParamFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.argo.sdk.protobuf.PAppRequestParam, com.argo.sdk.protobuf.PAppRequestParam.Builder, com.argo.sdk.protobuf.PAppRequestParamOrBuilder> 
        getParamFieldBuilder() {
      if (paramBuilder_ == null) {
        paramBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.argo.sdk.protobuf.PAppRequestParam, com.argo.sdk.protobuf.PAppRequestParam.Builder, com.argo.sdk.protobuf.PAppRequestParamOrBuilder>(
                param_,
                ((bitField0_ & 0x00000080) == 0x00000080),
                getParentForChildren(),
                isClean());
        param_ = null;
      }
      return paramBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:PAppRequest)
  }

  // @@protoc_insertion_point(class_scope:PAppRequest)
  private static final com.argo.sdk.protobuf.PAppRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.argo.sdk.protobuf.PAppRequest();
  }

  public static com.argo.sdk.protobuf.PAppRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<PAppRequest>
      PARSER = new com.google.protobuf.AbstractParser<PAppRequest>() {
    public PAppRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new PAppRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PAppRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PAppRequest> getParserForType() {
    return PARSER;
  }

  public com.argo.sdk.protobuf.PAppRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

