// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PAppRequest.proto

package com.argo.sdk.protobuf;

public interface PAppRequestParamOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PAppRequestParam)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional int32 intValue = 2;</code>
   */
  int getIntValue();

  /**
   * <code>optional string strValue = 3;</code>
   */
  java.lang.String getStrValue();
  /**
   * <code>optional string strValue = 3;</code>
   */
  com.google.protobuf.ByteString
      getStrValueBytes();

  /**
   * <code>optional int64 longValue = 4;</code>
   */
  long getLongValue();

  /**
   * <code>optional float floatValue = 5;</code>
   */
  float getFloatValue();

  /**
   * <code>optional bool boolValue = 6;</code>
   */
  boolean getBoolValue();

  /**
   * <code>optional bytes bytesValue = 7;</code>
   */
  com.google.protobuf.ByteString getBytesValue();
}
