// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PAppSession.proto

package com.argo.sdk.protobuf;

/**
 * Protobuf type {@code PAppSession}
 */
public  final class PAppSession extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:PAppSession)
    PAppSessionOrBuilder {
  // Use PAppSession.newBuilder() to construct.
  private PAppSession(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PAppSession() {
    sessionId_ = "";
    realName_ = "";
    userName_ = "";
    userId_ = 0L;
    secret_ = "";
    signinDate_ = "";
    profileImageUrl_ = "";
    appName_ = "";
    deviceName_ = "";
    deviceScreenSize_ = "";
    osName_ = "";
    osVersion_ = "";
    packageVersion_ = "";
    packageName_ = "";
    deviceId_ = "";
    deviceToken_ = "";
    apnsEnabled_ = 0;
    latesAppVers_ = "";
    localeIdentifier_ = "";
    latitude_ = 0F;
    longitude_ = 0F;
    cityId_ = 0;
    userKind_ = 0;
    userDemo_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private PAppSession(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            sessionId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            realName_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            userName_ = s;
            break;
          }
          case 32: {

            userId_ = input.readInt64();
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            secret_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            signinDate_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            profileImageUrl_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            appName_ = s;
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            deviceName_ = s;
            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();

            deviceScreenSize_ = s;
            break;
          }
          case 90: {
            java.lang.String s = input.readStringRequireUtf8();

            osName_ = s;
            break;
          }
          case 98: {
            java.lang.String s = input.readStringRequireUtf8();

            osVersion_ = s;
            break;
          }
          case 106: {
            java.lang.String s = input.readStringRequireUtf8();

            packageVersion_ = s;
            break;
          }
          case 114: {
            java.lang.String s = input.readStringRequireUtf8();

            packageName_ = s;
            break;
          }
          case 122: {
            java.lang.String s = input.readStringRequireUtf8();

            deviceId_ = s;
            break;
          }
          case 130: {
            java.lang.String s = input.readStringRequireUtf8();

            deviceToken_ = s;
            break;
          }
          case 136: {

            apnsEnabled_ = input.readInt32();
            break;
          }
          case 146: {
            java.lang.String s = input.readStringRequireUtf8();

            latesAppVers_ = s;
            break;
          }
          case 154: {
            java.lang.String s = input.readStringRequireUtf8();

            localeIdentifier_ = s;
            break;
          }
          case 165: {

            latitude_ = input.readFloat();
            break;
          }
          case 173: {

            longitude_ = input.readFloat();
            break;
          }
          case 176: {

            cityId_ = input.readInt32();
            break;
          }
          case 184: {

            userKind_ = input.readInt32();
            break;
          }
          case 192: {

            userDemo_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.argo.sdk.protobuf.PAppSessionProto.internal_static_PAppSession_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.argo.sdk.protobuf.PAppSessionProto.internal_static_PAppSession_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.argo.sdk.protobuf.PAppSession.class, com.argo.sdk.protobuf.PAppSession.Builder.class);
  }

  public static final int SESSIONID_FIELD_NUMBER = 1;
  private volatile java.lang.Object sessionId_;
  /**
   * <code>optional string sessionId = 1;</code>
   */
  public java.lang.String getSessionId() {
    java.lang.Object ref = sessionId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sessionId_ = s;
      return s;
    }
  }
  /**
   * <code>optional string sessionId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getSessionIdBytes() {
    java.lang.Object ref = sessionId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sessionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REALNAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object realName_;
  /**
   * <code>optional string realName = 2;</code>
   */
  public java.lang.String getRealName() {
    java.lang.Object ref = realName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      realName_ = s;
      return s;
    }
  }
  /**
   * <code>optional string realName = 2;</code>
   */
  public com.google.protobuf.ByteString
      getRealNameBytes() {
    java.lang.Object ref = realName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      realName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USERNAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object userName_;
  /**
   * <code>optional string userName = 3;</code>
   */
  public java.lang.String getUserName() {
    java.lang.Object ref = userName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userName_ = s;
      return s;
    }
  }
  /**
   * <code>optional string userName = 3;</code>
   */
  public com.google.protobuf.ByteString
      getUserNameBytes() {
    java.lang.Object ref = userName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USERID_FIELD_NUMBER = 4;
  private long userId_;
  /**
   * <code>optional int64 userId = 4;</code>
   */
  public long getUserId() {
    return userId_;
  }

  public static final int SECRET_FIELD_NUMBER = 5;
  private volatile java.lang.Object secret_;
  /**
   * <code>optional string secret = 5;</code>
   */
  public java.lang.String getSecret() {
    java.lang.Object ref = secret_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      secret_ = s;
      return s;
    }
  }
  /**
   * <code>optional string secret = 5;</code>
   */
  public com.google.protobuf.ByteString
      getSecretBytes() {
    java.lang.Object ref = secret_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      secret_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SIGNINDATE_FIELD_NUMBER = 6;
  private volatile java.lang.Object signinDate_;
  /**
   * <code>optional string signinDate = 6;</code>
   */
  public java.lang.String getSigninDate() {
    java.lang.Object ref = signinDate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      signinDate_ = s;
      return s;
    }
  }
  /**
   * <code>optional string signinDate = 6;</code>
   */
  public com.google.protobuf.ByteString
      getSigninDateBytes() {
    java.lang.Object ref = signinDate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      signinDate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PROFILEIMAGEURL_FIELD_NUMBER = 7;
  private volatile java.lang.Object profileImageUrl_;
  /**
   * <code>optional string profileImageUrl = 7;</code>
   */
  public java.lang.String getProfileImageUrl() {
    java.lang.Object ref = profileImageUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      profileImageUrl_ = s;
      return s;
    }
  }
  /**
   * <code>optional string profileImageUrl = 7;</code>
   */
  public com.google.protobuf.ByteString
      getProfileImageUrlBytes() {
    java.lang.Object ref = profileImageUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      profileImageUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int APPNAME_FIELD_NUMBER = 8;
  private volatile java.lang.Object appName_;
  /**
   * <code>optional string appName = 8;</code>
   */
  public java.lang.String getAppName() {
    java.lang.Object ref = appName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      appName_ = s;
      return s;
    }
  }
  /**
   * <code>optional string appName = 8;</code>
   */
  public com.google.protobuf.ByteString
      getAppNameBytes() {
    java.lang.Object ref = appName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      appName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEVICENAME_FIELD_NUMBER = 9;
  private volatile java.lang.Object deviceName_;
  /**
   * <code>optional string deviceName = 9;</code>
   */
  public java.lang.String getDeviceName() {
    java.lang.Object ref = deviceName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      deviceName_ = s;
      return s;
    }
  }
  /**
   * <code>optional string deviceName = 9;</code>
   */
  public com.google.protobuf.ByteString
      getDeviceNameBytes() {
    java.lang.Object ref = deviceName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      deviceName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEVICESCREENSIZE_FIELD_NUMBER = 10;
  private volatile java.lang.Object deviceScreenSize_;
  /**
   * <code>optional string deviceScreenSize = 10;</code>
   */
  public java.lang.String getDeviceScreenSize() {
    java.lang.Object ref = deviceScreenSize_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      deviceScreenSize_ = s;
      return s;
    }
  }
  /**
   * <code>optional string deviceScreenSize = 10;</code>
   */
  public com.google.protobuf.ByteString
      getDeviceScreenSizeBytes() {
    java.lang.Object ref = deviceScreenSize_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      deviceScreenSize_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OSNAME_FIELD_NUMBER = 11;
  private volatile java.lang.Object osName_;
  /**
   * <code>optional string osName = 11;</code>
   */
  public java.lang.String getOsName() {
    java.lang.Object ref = osName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      osName_ = s;
      return s;
    }
  }
  /**
   * <code>optional string osName = 11;</code>
   */
  public com.google.protobuf.ByteString
      getOsNameBytes() {
    java.lang.Object ref = osName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      osName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OSVERSION_FIELD_NUMBER = 12;
  private volatile java.lang.Object osVersion_;
  /**
   * <code>optional string osVersion = 12;</code>
   */
  public java.lang.String getOsVersion() {
    java.lang.Object ref = osVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      osVersion_ = s;
      return s;
    }
  }
  /**
   * <code>optional string osVersion = 12;</code>
   */
  public com.google.protobuf.ByteString
      getOsVersionBytes() {
    java.lang.Object ref = osVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      osVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PACKAGEVERSION_FIELD_NUMBER = 13;
  private volatile java.lang.Object packageVersion_;
  /**
   * <code>optional string packageVersion = 13;</code>
   */
  public java.lang.String getPackageVersion() {
    java.lang.Object ref = packageVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      packageVersion_ = s;
      return s;
    }
  }
  /**
   * <code>optional string packageVersion = 13;</code>
   */
  public com.google.protobuf.ByteString
      getPackageVersionBytes() {
    java.lang.Object ref = packageVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      packageVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PACKAGENAME_FIELD_NUMBER = 14;
  private volatile java.lang.Object packageName_;
  /**
   * <code>optional string packageName = 14;</code>
   */
  public java.lang.String getPackageName() {
    java.lang.Object ref = packageName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      packageName_ = s;
      return s;
    }
  }
  /**
   * <code>optional string packageName = 14;</code>
   */
  public com.google.protobuf.ByteString
      getPackageNameBytes() {
    java.lang.Object ref = packageName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      packageName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEVICEID_FIELD_NUMBER = 15;
  private volatile java.lang.Object deviceId_;
  /**
   * <code>optional string deviceId = 15;</code>
   */
  public java.lang.String getDeviceId() {
    java.lang.Object ref = deviceId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      deviceId_ = s;
      return s;
    }
  }
  /**
   * <code>optional string deviceId = 15;</code>
   */
  public com.google.protobuf.ByteString
      getDeviceIdBytes() {
    java.lang.Object ref = deviceId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      deviceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEVICETOKEN_FIELD_NUMBER = 16;
  private volatile java.lang.Object deviceToken_;
  /**
   * <code>optional string deviceToken = 16;</code>
   */
  public java.lang.String getDeviceToken() {
    java.lang.Object ref = deviceToken_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      deviceToken_ = s;
      return s;
    }
  }
  /**
   * <code>optional string deviceToken = 16;</code>
   */
  public com.google.protobuf.ByteString
      getDeviceTokenBytes() {
    java.lang.Object ref = deviceToken_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      deviceToken_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int APNSENABLED_FIELD_NUMBER = 17;
  private int apnsEnabled_;
  /**
   * <code>optional int32 apnsEnabled = 17;</code>
   */
  public int getApnsEnabled() {
    return apnsEnabled_;
  }

  public static final int LATESAPPVERS_FIELD_NUMBER = 18;
  private volatile java.lang.Object latesAppVers_;
  /**
   * <code>optional string latesAppVers = 18;</code>
   */
  public java.lang.String getLatesAppVers() {
    java.lang.Object ref = latesAppVers_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      latesAppVers_ = s;
      return s;
    }
  }
  /**
   * <code>optional string latesAppVers = 18;</code>
   */
  public com.google.protobuf.ByteString
      getLatesAppVersBytes() {
    java.lang.Object ref = latesAppVers_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      latesAppVers_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LOCALEIDENTIFIER_FIELD_NUMBER = 19;
  private volatile java.lang.Object localeIdentifier_;
  /**
   * <code>optional string localeIdentifier = 19;</code>
   */
  public java.lang.String getLocaleIdentifier() {
    java.lang.Object ref = localeIdentifier_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      localeIdentifier_ = s;
      return s;
    }
  }
  /**
   * <code>optional string localeIdentifier = 19;</code>
   */
  public com.google.protobuf.ByteString
      getLocaleIdentifierBytes() {
    java.lang.Object ref = localeIdentifier_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      localeIdentifier_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LATITUDE_FIELD_NUMBER = 20;
  private float latitude_;
  /**
   * <code>optional float latitude = 20;</code>
   */
  public float getLatitude() {
    return latitude_;
  }

  public static final int LONGITUDE_FIELD_NUMBER = 21;
  private float longitude_;
  /**
   * <code>optional float longitude = 21;</code>
   */
  public float getLongitude() {
    return longitude_;
  }

  public static final int CITYID_FIELD_NUMBER = 22;
  private int cityId_;
  /**
   * <code>optional int32 cityId = 22;</code>
   */
  public int getCityId() {
    return cityId_;
  }

  public static final int USERKIND_FIELD_NUMBER = 23;
  private int userKind_;
  /**
   * <code>optional int32 userKind = 23;</code>
   */
  public int getUserKind() {
    return userKind_;
  }

  public static final int USERDEMO_FIELD_NUMBER = 24;
  private int userDemo_;
  /**
   * <code>optional int32 userDemo = 24;</code>
   */
  public int getUserDemo() {
    return userDemo_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getSessionIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, sessionId_);
    }
    if (!getRealNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, realName_);
    }
    if (!getUserNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, userName_);
    }
    if (userId_ != 0L) {
      output.writeInt64(4, userId_);
    }
    if (!getSecretBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, secret_);
    }
    if (!getSigninDateBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, signinDate_);
    }
    if (!getProfileImageUrlBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, profileImageUrl_);
    }
    if (!getAppNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, appName_);
    }
    if (!getDeviceNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, deviceName_);
    }
    if (!getDeviceScreenSizeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, deviceScreenSize_);
    }
    if (!getOsNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, osName_);
    }
    if (!getOsVersionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, osVersion_);
    }
    if (!getPackageVersionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 13, packageVersion_);
    }
    if (!getPackageNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 14, packageName_);
    }
    if (!getDeviceIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 15, deviceId_);
    }
    if (!getDeviceTokenBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 16, deviceToken_);
    }
    if (apnsEnabled_ != 0) {
      output.writeInt32(17, apnsEnabled_);
    }
    if (!getLatesAppVersBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 18, latesAppVers_);
    }
    if (!getLocaleIdentifierBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 19, localeIdentifier_);
    }
    if (latitude_ != 0F) {
      output.writeFloat(20, latitude_);
    }
    if (longitude_ != 0F) {
      output.writeFloat(21, longitude_);
    }
    if (cityId_ != 0) {
      output.writeInt32(22, cityId_);
    }
    if (userKind_ != 0) {
      output.writeInt32(23, userKind_);
    }
    if (userDemo_ != 0) {
      output.writeInt32(24, userDemo_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getSessionIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, sessionId_);
    }
    if (!getRealNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, realName_);
    }
    if (!getUserNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, userName_);
    }
    if (userId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, userId_);
    }
    if (!getSecretBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, secret_);
    }
    if (!getSigninDateBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, signinDate_);
    }
    if (!getProfileImageUrlBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, profileImageUrl_);
    }
    if (!getAppNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, appName_);
    }
    if (!getDeviceNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, deviceName_);
    }
    if (!getDeviceScreenSizeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, deviceScreenSize_);
    }
    if (!getOsNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, osName_);
    }
    if (!getOsVersionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, osVersion_);
    }
    if (!getPackageVersionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, packageVersion_);
    }
    if (!getPackageNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, packageName_);
    }
    if (!getDeviceIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(15, deviceId_);
    }
    if (!getDeviceTokenBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(16, deviceToken_);
    }
    if (apnsEnabled_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(17, apnsEnabled_);
    }
    if (!getLatesAppVersBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(18, latesAppVers_);
    }
    if (!getLocaleIdentifierBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(19, localeIdentifier_);
    }
    if (latitude_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(20, latitude_);
    }
    if (longitude_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(21, longitude_);
    }
    if (cityId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(22, cityId_);
    }
    if (userKind_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(23, userKind_);
    }
    if (userDemo_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(24, userDemo_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.argo.sdk.protobuf.PAppSession)) {
      return super.equals(obj);
    }
    com.argo.sdk.protobuf.PAppSession other = (com.argo.sdk.protobuf.PAppSession) obj;

    boolean result = true;
    result = result && getSessionId()
        .equals(other.getSessionId());
    result = result && getRealName()
        .equals(other.getRealName());
    result = result && getUserName()
        .equals(other.getUserName());
    result = result && (getUserId()
        == other.getUserId());
    result = result && getSecret()
        .equals(other.getSecret());
    result = result && getSigninDate()
        .equals(other.getSigninDate());
    result = result && getProfileImageUrl()
        .equals(other.getProfileImageUrl());
    result = result && getAppName()
        .equals(other.getAppName());
    result = result && getDeviceName()
        .equals(other.getDeviceName());
    result = result && getDeviceScreenSize()
        .equals(other.getDeviceScreenSize());
    result = result && getOsName()
        .equals(other.getOsName());
    result = result && getOsVersion()
        .equals(other.getOsVersion());
    result = result && getPackageVersion()
        .equals(other.getPackageVersion());
    result = result && getPackageName()
        .equals(other.getPackageName());
    result = result && getDeviceId()
        .equals(other.getDeviceId());
    result = result && getDeviceToken()
        .equals(other.getDeviceToken());
    result = result && (getApnsEnabled()
        == other.getApnsEnabled());
    result = result && getLatesAppVers()
        .equals(other.getLatesAppVers());
    result = result && getLocaleIdentifier()
        .equals(other.getLocaleIdentifier());
    result = result && (
        java.lang.Float.floatToIntBits(getLatitude())
        == java.lang.Float.floatToIntBits(
            other.getLatitude()));
    result = result && (
        java.lang.Float.floatToIntBits(getLongitude())
        == java.lang.Float.floatToIntBits(
            other.getLongitude()));
    result = result && (getCityId()
        == other.getCityId());
    result = result && (getUserKind()
        == other.getUserKind());
    result = result && (getUserDemo()
        == other.getUserDemo());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + SESSIONID_FIELD_NUMBER;
    hash = (53 * hash) + getSessionId().hashCode();
    hash = (37 * hash) + REALNAME_FIELD_NUMBER;
    hash = (53 * hash) + getRealName().hashCode();
    hash = (37 * hash) + USERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getUserName().hashCode();
    hash = (37 * hash) + USERID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUserId());
    hash = (37 * hash) + SECRET_FIELD_NUMBER;
    hash = (53 * hash) + getSecret().hashCode();
    hash = (37 * hash) + SIGNINDATE_FIELD_NUMBER;
    hash = (53 * hash) + getSigninDate().hashCode();
    hash = (37 * hash) + PROFILEIMAGEURL_FIELD_NUMBER;
    hash = (53 * hash) + getProfileImageUrl().hashCode();
    hash = (37 * hash) + APPNAME_FIELD_NUMBER;
    hash = (53 * hash) + getAppName().hashCode();
    hash = (37 * hash) + DEVICENAME_FIELD_NUMBER;
    hash = (53 * hash) + getDeviceName().hashCode();
    hash = (37 * hash) + DEVICESCREENSIZE_FIELD_NUMBER;
    hash = (53 * hash) + getDeviceScreenSize().hashCode();
    hash = (37 * hash) + OSNAME_FIELD_NUMBER;
    hash = (53 * hash) + getOsName().hashCode();
    hash = (37 * hash) + OSVERSION_FIELD_NUMBER;
    hash = (53 * hash) + getOsVersion().hashCode();
    hash = (37 * hash) + PACKAGEVERSION_FIELD_NUMBER;
    hash = (53 * hash) + getPackageVersion().hashCode();
    hash = (37 * hash) + PACKAGENAME_FIELD_NUMBER;
    hash = (53 * hash) + getPackageName().hashCode();
    hash = (37 * hash) + DEVICEID_FIELD_NUMBER;
    hash = (53 * hash) + getDeviceId().hashCode();
    hash = (37 * hash) + DEVICETOKEN_FIELD_NUMBER;
    hash = (53 * hash) + getDeviceToken().hashCode();
    hash = (37 * hash) + APNSENABLED_FIELD_NUMBER;
    hash = (53 * hash) + getApnsEnabled();
    hash = (37 * hash) + LATESAPPVERS_FIELD_NUMBER;
    hash = (53 * hash) + getLatesAppVers().hashCode();
    hash = (37 * hash) + LOCALEIDENTIFIER_FIELD_NUMBER;
    hash = (53 * hash) + getLocaleIdentifier().hashCode();
    hash = (37 * hash) + LATITUDE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getLatitude());
    hash = (37 * hash) + LONGITUDE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getLongitude());
    hash = (37 * hash) + CITYID_FIELD_NUMBER;
    hash = (53 * hash) + getCityId();
    hash = (37 * hash) + USERKIND_FIELD_NUMBER;
    hash = (53 * hash) + getUserKind();
    hash = (37 * hash) + USERDEMO_FIELD_NUMBER;
    hash = (53 * hash) + getUserDemo();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.argo.sdk.protobuf.PAppSession parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.argo.sdk.protobuf.PAppSession parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.argo.sdk.protobuf.PAppSession parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.argo.sdk.protobuf.PAppSession parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.argo.sdk.protobuf.PAppSession parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.argo.sdk.protobuf.PAppSession parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.argo.sdk.protobuf.PAppSession parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.argo.sdk.protobuf.PAppSession parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.argo.sdk.protobuf.PAppSession parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.argo.sdk.protobuf.PAppSession parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.argo.sdk.protobuf.PAppSession prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code PAppSession}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PAppSession)
      com.argo.sdk.protobuf.PAppSessionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.argo.sdk.protobuf.PAppSessionProto.internal_static_PAppSession_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.argo.sdk.protobuf.PAppSessionProto.internal_static_PAppSession_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.argo.sdk.protobuf.PAppSession.class, com.argo.sdk.protobuf.PAppSession.Builder.class);
    }

    // Construct using com.argo.sdk.protobuf.PAppSession.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      sessionId_ = "";

      realName_ = "";

      userName_ = "";

      userId_ = 0L;

      secret_ = "";

      signinDate_ = "";

      profileImageUrl_ = "";

      appName_ = "";

      deviceName_ = "";

      deviceScreenSize_ = "";

      osName_ = "";

      osVersion_ = "";

      packageVersion_ = "";

      packageName_ = "";

      deviceId_ = "";

      deviceToken_ = "";

      apnsEnabled_ = 0;

      latesAppVers_ = "";

      localeIdentifier_ = "";

      latitude_ = 0F;

      longitude_ = 0F;

      cityId_ = 0;

      userKind_ = 0;

      userDemo_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.argo.sdk.protobuf.PAppSessionProto.internal_static_PAppSession_descriptor;
    }

    public com.argo.sdk.protobuf.PAppSession getDefaultInstanceForType() {
      return com.argo.sdk.protobuf.PAppSession.getDefaultInstance();
    }

    public com.argo.sdk.protobuf.PAppSession build() {
      com.argo.sdk.protobuf.PAppSession result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.argo.sdk.protobuf.PAppSession buildPartial() {
      com.argo.sdk.protobuf.PAppSession result = new com.argo.sdk.protobuf.PAppSession(this);
      result.sessionId_ = sessionId_;
      result.realName_ = realName_;
      result.userName_ = userName_;
      result.userId_ = userId_;
      result.secret_ = secret_;
      result.signinDate_ = signinDate_;
      result.profileImageUrl_ = profileImageUrl_;
      result.appName_ = appName_;
      result.deviceName_ = deviceName_;
      result.deviceScreenSize_ = deviceScreenSize_;
      result.osName_ = osName_;
      result.osVersion_ = osVersion_;
      result.packageVersion_ = packageVersion_;
      result.packageName_ = packageName_;
      result.deviceId_ = deviceId_;
      result.deviceToken_ = deviceToken_;
      result.apnsEnabled_ = apnsEnabled_;
      result.latesAppVers_ = latesAppVers_;
      result.localeIdentifier_ = localeIdentifier_;
      result.latitude_ = latitude_;
      result.longitude_ = longitude_;
      result.cityId_ = cityId_;
      result.userKind_ = userKind_;
      result.userDemo_ = userDemo_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.argo.sdk.protobuf.PAppSession) {
        return mergeFrom((com.argo.sdk.protobuf.PAppSession)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.argo.sdk.protobuf.PAppSession other) {
      if (other == com.argo.sdk.protobuf.PAppSession.getDefaultInstance()) return this;
      if (!other.getSessionId().isEmpty()) {
        sessionId_ = other.sessionId_;
        onChanged();
      }
      if (!other.getRealName().isEmpty()) {
        realName_ = other.realName_;
        onChanged();
      }
      if (!other.getUserName().isEmpty()) {
        userName_ = other.userName_;
        onChanged();
      }
      if (other.getUserId() != 0L) {
        setUserId(other.getUserId());
      }
      if (!other.getSecret().isEmpty()) {
        secret_ = other.secret_;
        onChanged();
      }
      if (!other.getSigninDate().isEmpty()) {
        signinDate_ = other.signinDate_;
        onChanged();
      }
      if (!other.getProfileImageUrl().isEmpty()) {
        profileImageUrl_ = other.profileImageUrl_;
        onChanged();
      }
      if (!other.getAppName().isEmpty()) {
        appName_ = other.appName_;
        onChanged();
      }
      if (!other.getDeviceName().isEmpty()) {
        deviceName_ = other.deviceName_;
        onChanged();
      }
      if (!other.getDeviceScreenSize().isEmpty()) {
        deviceScreenSize_ = other.deviceScreenSize_;
        onChanged();
      }
      if (!other.getOsName().isEmpty()) {
        osName_ = other.osName_;
        onChanged();
      }
      if (!other.getOsVersion().isEmpty()) {
        osVersion_ = other.osVersion_;
        onChanged();
      }
      if (!other.getPackageVersion().isEmpty()) {
        packageVersion_ = other.packageVersion_;
        onChanged();
      }
      if (!other.getPackageName().isEmpty()) {
        packageName_ = other.packageName_;
        onChanged();
      }
      if (!other.getDeviceId().isEmpty()) {
        deviceId_ = other.deviceId_;
        onChanged();
      }
      if (!other.getDeviceToken().isEmpty()) {
        deviceToken_ = other.deviceToken_;
        onChanged();
      }
      if (other.getApnsEnabled() != 0) {
        setApnsEnabled(other.getApnsEnabled());
      }
      if (!other.getLatesAppVers().isEmpty()) {
        latesAppVers_ = other.latesAppVers_;
        onChanged();
      }
      if (!other.getLocaleIdentifier().isEmpty()) {
        localeIdentifier_ = other.localeIdentifier_;
        onChanged();
      }
      if (other.getLatitude() != 0F) {
        setLatitude(other.getLatitude());
      }
      if (other.getLongitude() != 0F) {
        setLongitude(other.getLongitude());
      }
      if (other.getCityId() != 0) {
        setCityId(other.getCityId());
      }
      if (other.getUserKind() != 0) {
        setUserKind(other.getUserKind());
      }
      if (other.getUserDemo() != 0) {
        setUserDemo(other.getUserDemo());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.argo.sdk.protobuf.PAppSession parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.argo.sdk.protobuf.PAppSession) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object sessionId_ = "";
    /**
     * <code>optional string sessionId = 1;</code>
     */
    public java.lang.String getSessionId() {
      java.lang.Object ref = sessionId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sessionId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string sessionId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSessionIdBytes() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string sessionId = 1;</code>
     */
    public Builder setSessionId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sessionId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string sessionId = 1;</code>
     */
    public Builder clearSessionId() {
      
      sessionId_ = getDefaultInstance().getSessionId();
      onChanged();
      return this;
    }
    /**
     * <code>optional string sessionId = 1;</code>
     */
    public Builder setSessionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sessionId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object realName_ = "";
    /**
     * <code>optional string realName = 2;</code>
     */
    public java.lang.String getRealName() {
      java.lang.Object ref = realName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        realName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string realName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getRealNameBytes() {
      java.lang.Object ref = realName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        realName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string realName = 2;</code>
     */
    public Builder setRealName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      realName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string realName = 2;</code>
     */
    public Builder clearRealName() {
      
      realName_ = getDefaultInstance().getRealName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string realName = 2;</code>
     */
    public Builder setRealNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      realName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object userName_ = "";
    /**
     * <code>optional string userName = 3;</code>
     */
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string userName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string userName = 3;</code>
     */
    public Builder setUserName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string userName = 3;</code>
     */
    public Builder clearUserName() {
      
      userName_ = getDefaultInstance().getUserName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string userName = 3;</code>
     */
    public Builder setUserNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userName_ = value;
      onChanged();
      return this;
    }

    private long userId_ ;
    /**
     * <code>optional int64 userId = 4;</code>
     */
    public long getUserId() {
      return userId_;
    }
    /**
     * <code>optional int64 userId = 4;</code>
     */
    public Builder setUserId(long value) {
      
      userId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 userId = 4;</code>
     */
    public Builder clearUserId() {
      
      userId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object secret_ = "";
    /**
     * <code>optional string secret = 5;</code>
     */
    public java.lang.String getSecret() {
      java.lang.Object ref = secret_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        secret_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string secret = 5;</code>
     */
    public com.google.protobuf.ByteString
        getSecretBytes() {
      java.lang.Object ref = secret_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        secret_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string secret = 5;</code>
     */
    public Builder setSecret(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      secret_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string secret = 5;</code>
     */
    public Builder clearSecret() {
      
      secret_ = getDefaultInstance().getSecret();
      onChanged();
      return this;
    }
    /**
     * <code>optional string secret = 5;</code>
     */
    public Builder setSecretBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      secret_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object signinDate_ = "";
    /**
     * <code>optional string signinDate = 6;</code>
     */
    public java.lang.String getSigninDate() {
      java.lang.Object ref = signinDate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        signinDate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string signinDate = 6;</code>
     */
    public com.google.protobuf.ByteString
        getSigninDateBytes() {
      java.lang.Object ref = signinDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        signinDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string signinDate = 6;</code>
     */
    public Builder setSigninDate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      signinDate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string signinDate = 6;</code>
     */
    public Builder clearSigninDate() {
      
      signinDate_ = getDefaultInstance().getSigninDate();
      onChanged();
      return this;
    }
    /**
     * <code>optional string signinDate = 6;</code>
     */
    public Builder setSigninDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      signinDate_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object profileImageUrl_ = "";
    /**
     * <code>optional string profileImageUrl = 7;</code>
     */
    public java.lang.String getProfileImageUrl() {
      java.lang.Object ref = profileImageUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        profileImageUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string profileImageUrl = 7;</code>
     */
    public com.google.protobuf.ByteString
        getProfileImageUrlBytes() {
      java.lang.Object ref = profileImageUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        profileImageUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string profileImageUrl = 7;</code>
     */
    public Builder setProfileImageUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      profileImageUrl_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string profileImageUrl = 7;</code>
     */
    public Builder clearProfileImageUrl() {
      
      profileImageUrl_ = getDefaultInstance().getProfileImageUrl();
      onChanged();
      return this;
    }
    /**
     * <code>optional string profileImageUrl = 7;</code>
     */
    public Builder setProfileImageUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      profileImageUrl_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object appName_ = "";
    /**
     * <code>optional string appName = 8;</code>
     */
    public java.lang.String getAppName() {
      java.lang.Object ref = appName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string appName = 8;</code>
     */
    public com.google.protobuf.ByteString
        getAppNameBytes() {
      java.lang.Object ref = appName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string appName = 8;</code>
     */
    public Builder setAppName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      appName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string appName = 8;</code>
     */
    public Builder clearAppName() {
      
      appName_ = getDefaultInstance().getAppName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string appName = 8;</code>
     */
    public Builder setAppNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      appName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object deviceName_ = "";
    /**
     * <code>optional string deviceName = 9;</code>
     */
    public java.lang.String getDeviceName() {
      java.lang.Object ref = deviceName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string deviceName = 9;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceNameBytes() {
      java.lang.Object ref = deviceName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string deviceName = 9;</code>
     */
    public Builder setDeviceName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      deviceName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string deviceName = 9;</code>
     */
    public Builder clearDeviceName() {
      
      deviceName_ = getDefaultInstance().getDeviceName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string deviceName = 9;</code>
     */
    public Builder setDeviceNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      deviceName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object deviceScreenSize_ = "";
    /**
     * <code>optional string deviceScreenSize = 10;</code>
     */
    public java.lang.String getDeviceScreenSize() {
      java.lang.Object ref = deviceScreenSize_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceScreenSize_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string deviceScreenSize = 10;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceScreenSizeBytes() {
      java.lang.Object ref = deviceScreenSize_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceScreenSize_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string deviceScreenSize = 10;</code>
     */
    public Builder setDeviceScreenSize(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      deviceScreenSize_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string deviceScreenSize = 10;</code>
     */
    public Builder clearDeviceScreenSize() {
      
      deviceScreenSize_ = getDefaultInstance().getDeviceScreenSize();
      onChanged();
      return this;
    }
    /**
     * <code>optional string deviceScreenSize = 10;</code>
     */
    public Builder setDeviceScreenSizeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      deviceScreenSize_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object osName_ = "";
    /**
     * <code>optional string osName = 11;</code>
     */
    public java.lang.String getOsName() {
      java.lang.Object ref = osName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        osName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string osName = 11;</code>
     */
    public com.google.protobuf.ByteString
        getOsNameBytes() {
      java.lang.Object ref = osName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        osName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string osName = 11;</code>
     */
    public Builder setOsName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      osName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string osName = 11;</code>
     */
    public Builder clearOsName() {
      
      osName_ = getDefaultInstance().getOsName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string osName = 11;</code>
     */
    public Builder setOsNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      osName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object osVersion_ = "";
    /**
     * <code>optional string osVersion = 12;</code>
     */
    public java.lang.String getOsVersion() {
      java.lang.Object ref = osVersion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        osVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string osVersion = 12;</code>
     */
    public com.google.protobuf.ByteString
        getOsVersionBytes() {
      java.lang.Object ref = osVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        osVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string osVersion = 12;</code>
     */
    public Builder setOsVersion(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      osVersion_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string osVersion = 12;</code>
     */
    public Builder clearOsVersion() {
      
      osVersion_ = getDefaultInstance().getOsVersion();
      onChanged();
      return this;
    }
    /**
     * <code>optional string osVersion = 12;</code>
     */
    public Builder setOsVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      osVersion_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object packageVersion_ = "";
    /**
     * <code>optional string packageVersion = 13;</code>
     */
    public java.lang.String getPackageVersion() {
      java.lang.Object ref = packageVersion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        packageVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string packageVersion = 13;</code>
     */
    public com.google.protobuf.ByteString
        getPackageVersionBytes() {
      java.lang.Object ref = packageVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        packageVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string packageVersion = 13;</code>
     */
    public Builder setPackageVersion(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      packageVersion_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string packageVersion = 13;</code>
     */
    public Builder clearPackageVersion() {
      
      packageVersion_ = getDefaultInstance().getPackageVersion();
      onChanged();
      return this;
    }
    /**
     * <code>optional string packageVersion = 13;</code>
     */
    public Builder setPackageVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      packageVersion_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object packageName_ = "";
    /**
     * <code>optional string packageName = 14;</code>
     */
    public java.lang.String getPackageName() {
      java.lang.Object ref = packageName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        packageName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string packageName = 14;</code>
     */
    public com.google.protobuf.ByteString
        getPackageNameBytes() {
      java.lang.Object ref = packageName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        packageName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string packageName = 14;</code>
     */
    public Builder setPackageName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      packageName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string packageName = 14;</code>
     */
    public Builder clearPackageName() {
      
      packageName_ = getDefaultInstance().getPackageName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string packageName = 14;</code>
     */
    public Builder setPackageNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      packageName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object deviceId_ = "";
    /**
     * <code>optional string deviceId = 15;</code>
     */
    public java.lang.String getDeviceId() {
      java.lang.Object ref = deviceId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string deviceId = 15;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string deviceId = 15;</code>
     */
    public Builder setDeviceId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      deviceId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string deviceId = 15;</code>
     */
    public Builder clearDeviceId() {
      
      deviceId_ = getDefaultInstance().getDeviceId();
      onChanged();
      return this;
    }
    /**
     * <code>optional string deviceId = 15;</code>
     */
    public Builder setDeviceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      deviceId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object deviceToken_ = "";
    /**
     * <code>optional string deviceToken = 16;</code>
     */
    public java.lang.String getDeviceToken() {
      java.lang.Object ref = deviceToken_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceToken_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string deviceToken = 16;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceTokenBytes() {
      java.lang.Object ref = deviceToken_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string deviceToken = 16;</code>
     */
    public Builder setDeviceToken(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      deviceToken_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string deviceToken = 16;</code>
     */
    public Builder clearDeviceToken() {
      
      deviceToken_ = getDefaultInstance().getDeviceToken();
      onChanged();
      return this;
    }
    /**
     * <code>optional string deviceToken = 16;</code>
     */
    public Builder setDeviceTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      deviceToken_ = value;
      onChanged();
      return this;
    }

    private int apnsEnabled_ ;
    /**
     * <code>optional int32 apnsEnabled = 17;</code>
     */
    public int getApnsEnabled() {
      return apnsEnabled_;
    }
    /**
     * <code>optional int32 apnsEnabled = 17;</code>
     */
    public Builder setApnsEnabled(int value) {
      
      apnsEnabled_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 apnsEnabled = 17;</code>
     */
    public Builder clearApnsEnabled() {
      
      apnsEnabled_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object latesAppVers_ = "";
    /**
     * <code>optional string latesAppVers = 18;</code>
     */
    public java.lang.String getLatesAppVers() {
      java.lang.Object ref = latesAppVers_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        latesAppVers_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string latesAppVers = 18;</code>
     */
    public com.google.protobuf.ByteString
        getLatesAppVersBytes() {
      java.lang.Object ref = latesAppVers_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        latesAppVers_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string latesAppVers = 18;</code>
     */
    public Builder setLatesAppVers(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      latesAppVers_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string latesAppVers = 18;</code>
     */
    public Builder clearLatesAppVers() {
      
      latesAppVers_ = getDefaultInstance().getLatesAppVers();
      onChanged();
      return this;
    }
    /**
     * <code>optional string latesAppVers = 18;</code>
     */
    public Builder setLatesAppVersBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      latesAppVers_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object localeIdentifier_ = "";
    /**
     * <code>optional string localeIdentifier = 19;</code>
     */
    public java.lang.String getLocaleIdentifier() {
      java.lang.Object ref = localeIdentifier_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        localeIdentifier_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string localeIdentifier = 19;</code>
     */
    public com.google.protobuf.ByteString
        getLocaleIdentifierBytes() {
      java.lang.Object ref = localeIdentifier_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        localeIdentifier_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string localeIdentifier = 19;</code>
     */
    public Builder setLocaleIdentifier(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      localeIdentifier_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string localeIdentifier = 19;</code>
     */
    public Builder clearLocaleIdentifier() {
      
      localeIdentifier_ = getDefaultInstance().getLocaleIdentifier();
      onChanged();
      return this;
    }
    /**
     * <code>optional string localeIdentifier = 19;</code>
     */
    public Builder setLocaleIdentifierBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      localeIdentifier_ = value;
      onChanged();
      return this;
    }

    private float latitude_ ;
    /**
     * <code>optional float latitude = 20;</code>
     */
    public float getLatitude() {
      return latitude_;
    }
    /**
     * <code>optional float latitude = 20;</code>
     */
    public Builder setLatitude(float value) {
      
      latitude_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional float latitude = 20;</code>
     */
    public Builder clearLatitude() {
      
      latitude_ = 0F;
      onChanged();
      return this;
    }

    private float longitude_ ;
    /**
     * <code>optional float longitude = 21;</code>
     */
    public float getLongitude() {
      return longitude_;
    }
    /**
     * <code>optional float longitude = 21;</code>
     */
    public Builder setLongitude(float value) {
      
      longitude_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional float longitude = 21;</code>
     */
    public Builder clearLongitude() {
      
      longitude_ = 0F;
      onChanged();
      return this;
    }

    private int cityId_ ;
    /**
     * <code>optional int32 cityId = 22;</code>
     */
    public int getCityId() {
      return cityId_;
    }
    /**
     * <code>optional int32 cityId = 22;</code>
     */
    public Builder setCityId(int value) {
      
      cityId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 cityId = 22;</code>
     */
    public Builder clearCityId() {
      
      cityId_ = 0;
      onChanged();
      return this;
    }

    private int userKind_ ;
    /**
     * <code>optional int32 userKind = 23;</code>
     */
    public int getUserKind() {
      return userKind_;
    }
    /**
     * <code>optional int32 userKind = 23;</code>
     */
    public Builder setUserKind(int value) {
      
      userKind_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 userKind = 23;</code>
     */
    public Builder clearUserKind() {
      
      userKind_ = 0;
      onChanged();
      return this;
    }

    private int userDemo_ ;
    /**
     * <code>optional int32 userDemo = 24;</code>
     */
    public int getUserDemo() {
      return userDemo_;
    }
    /**
     * <code>optional int32 userDemo = 24;</code>
     */
    public Builder setUserDemo(int value) {
      
      userDemo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 userDemo = 24;</code>
     */
    public Builder clearUserDemo() {
      
      userDemo_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:PAppSession)
  }

  // @@protoc_insertion_point(class_scope:PAppSession)
  private static final com.argo.sdk.protobuf.PAppSession DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.argo.sdk.protobuf.PAppSession();
  }

  public static com.argo.sdk.protobuf.PAppSession getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PAppSession>
      PARSER = new com.google.protobuf.AbstractParser<PAppSession>() {
    public PAppSession parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new PAppSession(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PAppSession> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PAppSession> getParserForType() {
    return PARSER;
  }

  public com.argo.sdk.protobuf.PAppSession getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

