// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PAppRequest.proto

package com.argo.sdk.protobuf;

/**
 * Protobuf type {@code PAppRequest}
 */
public  final class PAppRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:PAppRequest)
    PAppRequestOrBuilder {
  // Use PAppRequest.newBuilder() to construct.
  private PAppRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PAppRequest() {
    authId_ = "";
    sessionId_ = "";
    version_ = 0;
    sign_ = "";
    nonce_ = "";
    userAgent_ = "";
    path_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private PAppRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            authId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            sessionId_ = s;
            break;
          }
          case 24: {

            version_ = input.readInt32();
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            sign_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            nonce_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            userAgent_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            path_ = s;
            break;
          }
          case 66: {
            com.argo.sdk.protobuf.PAppRequestParam.Builder subBuilder = null;
            if (param_ != null) {
              subBuilder = param_.toBuilder();
            }
            param_ = input.readMessage(com.argo.sdk.protobuf.PAppRequestParam.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(param_);
              param_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.argo.sdk.protobuf.PAppRequestProto.internal_static_PAppRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.argo.sdk.protobuf.PAppRequestProto.internal_static_PAppRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.argo.sdk.protobuf.PAppRequest.class, com.argo.sdk.protobuf.PAppRequest.Builder.class);
  }

  public static final int AUTHID_FIELD_NUMBER = 1;
  private volatile java.lang.Object authId_;
  /**
   * <code>optional string authId = 1;</code>
   */
  public java.lang.String getAuthId() {
    java.lang.Object ref = authId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      authId_ = s;
      return s;
    }
  }
  /**
   * <code>optional string authId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getAuthIdBytes() {
    java.lang.Object ref = authId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      authId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SESSIONID_FIELD_NUMBER = 2;
  private volatile java.lang.Object sessionId_;
  /**
   * <code>optional string sessionId = 2;</code>
   */
  public java.lang.String getSessionId() {
    java.lang.Object ref = sessionId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sessionId_ = s;
      return s;
    }
  }
  /**
   * <code>optional string sessionId = 2;</code>
   */
  public com.google.protobuf.ByteString
      getSessionIdBytes() {
    java.lang.Object ref = sessionId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sessionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VERSION_FIELD_NUMBER = 3;
  private int version_;
  /**
   * <code>optional int32 version = 3;</code>
   */
  public int getVersion() {
    return version_;
  }

  public static final int SIGN_FIELD_NUMBER = 4;
  private volatile java.lang.Object sign_;
  /**
   * <code>optional string sign = 4;</code>
   */
  public java.lang.String getSign() {
    java.lang.Object ref = sign_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sign_ = s;
      return s;
    }
  }
  /**
   * <code>optional string sign = 4;</code>
   */
  public com.google.protobuf.ByteString
      getSignBytes() {
    java.lang.Object ref = sign_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sign_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NONCE_FIELD_NUMBER = 5;
  private volatile java.lang.Object nonce_;
  /**
   * <code>optional string nonce = 5;</code>
   */
  public java.lang.String getNonce() {
    java.lang.Object ref = nonce_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nonce_ = s;
      return s;
    }
  }
  /**
   * <code>optional string nonce = 5;</code>
   */
  public com.google.protobuf.ByteString
      getNonceBytes() {
    java.lang.Object ref = nonce_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nonce_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USERAGENT_FIELD_NUMBER = 6;
  private volatile java.lang.Object userAgent_;
  /**
   * <code>optional string userAgent = 6;</code>
   */
  public java.lang.String getUserAgent() {
    java.lang.Object ref = userAgent_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userAgent_ = s;
      return s;
    }
  }
  /**
   * <code>optional string userAgent = 6;</code>
   */
  public com.google.protobuf.ByteString
      getUserAgentBytes() {
    java.lang.Object ref = userAgent_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userAgent_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PATH_FIELD_NUMBER = 7;
  private volatile java.lang.Object path_;
  /**
   * <code>optional string path = 7;</code>
   */
  public java.lang.String getPath() {
    java.lang.Object ref = path_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      path_ = s;
      return s;
    }
  }
  /**
   * <code>optional string path = 7;</code>
   */
  public com.google.protobuf.ByteString
      getPathBytes() {
    java.lang.Object ref = path_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      path_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PARAM_FIELD_NUMBER = 8;
  private com.argo.sdk.protobuf.PAppRequestParam param_;
  /**
   * <code>optional .PAppRequestParam param = 8;</code>
   */
  public boolean hasParam() {
    return param_ != null;
  }
  /**
   * <code>optional .PAppRequestParam param = 8;</code>
   */
  public com.argo.sdk.protobuf.PAppRequestParam getParam() {
    return param_ == null ? com.argo.sdk.protobuf.PAppRequestParam.getDefaultInstance() : param_;
  }
  /**
   * <code>optional .PAppRequestParam param = 8;</code>
   */
  public com.argo.sdk.protobuf.PAppRequestParamOrBuilder getParamOrBuilder() {
    return getParam();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getAuthIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, authId_);
    }
    if (!getSessionIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, sessionId_);
    }
    if (version_ != 0) {
      output.writeInt32(3, version_);
    }
    if (!getSignBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, sign_);
    }
    if (!getNonceBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, nonce_);
    }
    if (!getUserAgentBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, userAgent_);
    }
    if (!getPathBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, path_);
    }
    if (param_ != null) {
      output.writeMessage(8, getParam());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getAuthIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, authId_);
    }
    if (!getSessionIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, sessionId_);
    }
    if (version_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, version_);
    }
    if (!getSignBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, sign_);
    }
    if (!getNonceBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, nonce_);
    }
    if (!getUserAgentBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, userAgent_);
    }
    if (!getPathBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, path_);
    }
    if (param_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getParam());
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.argo.sdk.protobuf.PAppRequest)) {
      return super.equals(obj);
    }
    com.argo.sdk.protobuf.PAppRequest other = (com.argo.sdk.protobuf.PAppRequest) obj;

    boolean result = true;
    result = result && getAuthId()
        .equals(other.getAuthId());
    result = result && getSessionId()
        .equals(other.getSessionId());
    result = result && (getVersion()
        == other.getVersion());
    result = result && getSign()
        .equals(other.getSign());
    result = result && getNonce()
        .equals(other.getNonce());
    result = result && getUserAgent()
        .equals(other.getUserAgent());
    result = result && getPath()
        .equals(other.getPath());
    result = result && (hasParam() == other.hasParam());
    if (hasParam()) {
      result = result && getParam()
          .equals(other.getParam());
    }
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + AUTHID_FIELD_NUMBER;
    hash = (53 * hash) + getAuthId().hashCode();
    hash = (37 * hash) + SESSIONID_FIELD_NUMBER;
    hash = (53 * hash) + getSessionId().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion();
    hash = (37 * hash) + SIGN_FIELD_NUMBER;
    hash = (53 * hash) + getSign().hashCode();
    hash = (37 * hash) + NONCE_FIELD_NUMBER;
    hash = (53 * hash) + getNonce().hashCode();
    hash = (37 * hash) + USERAGENT_FIELD_NUMBER;
    hash = (53 * hash) + getUserAgent().hashCode();
    hash = (37 * hash) + PATH_FIELD_NUMBER;
    hash = (53 * hash) + getPath().hashCode();
    if (hasParam()) {
      hash = (37 * hash) + PARAM_FIELD_NUMBER;
      hash = (53 * hash) + getParam().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.argo.sdk.protobuf.PAppRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.argo.sdk.protobuf.PAppRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.argo.sdk.protobuf.PAppRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.argo.sdk.protobuf.PAppRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.argo.sdk.protobuf.PAppRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.argo.sdk.protobuf.PAppRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.argo.sdk.protobuf.PAppRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.argo.sdk.protobuf.PAppRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.argo.sdk.protobuf.PAppRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.argo.sdk.protobuf.PAppRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.argo.sdk.protobuf.PAppRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code PAppRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PAppRequest)
      com.argo.sdk.protobuf.PAppRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.argo.sdk.protobuf.PAppRequestProto.internal_static_PAppRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.argo.sdk.protobuf.PAppRequestProto.internal_static_PAppRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.argo.sdk.protobuf.PAppRequest.class, com.argo.sdk.protobuf.PAppRequest.Builder.class);
    }

    // Construct using com.argo.sdk.protobuf.PAppRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      authId_ = "";

      sessionId_ = "";

      version_ = 0;

      sign_ = "";

      nonce_ = "";

      userAgent_ = "";

      path_ = "";

      if (paramBuilder_ == null) {
        param_ = null;
      } else {
        param_ = null;
        paramBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.argo.sdk.protobuf.PAppRequestProto.internal_static_PAppRequest_descriptor;
    }

    public com.argo.sdk.protobuf.PAppRequest getDefaultInstanceForType() {
      return com.argo.sdk.protobuf.PAppRequest.getDefaultInstance();
    }

    public com.argo.sdk.protobuf.PAppRequest build() {
      com.argo.sdk.protobuf.PAppRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.argo.sdk.protobuf.PAppRequest buildPartial() {
      com.argo.sdk.protobuf.PAppRequest result = new com.argo.sdk.protobuf.PAppRequest(this);
      result.authId_ = authId_;
      result.sessionId_ = sessionId_;
      result.version_ = version_;
      result.sign_ = sign_;
      result.nonce_ = nonce_;
      result.userAgent_ = userAgent_;
      result.path_ = path_;
      if (paramBuilder_ == null) {
        result.param_ = param_;
      } else {
        result.param_ = paramBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.argo.sdk.protobuf.PAppRequest) {
        return mergeFrom((com.argo.sdk.protobuf.PAppRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.argo.sdk.protobuf.PAppRequest other) {
      if (other == com.argo.sdk.protobuf.PAppRequest.getDefaultInstance()) return this;
      if (!other.getAuthId().isEmpty()) {
        authId_ = other.authId_;
        onChanged();
      }
      if (!other.getSessionId().isEmpty()) {
        sessionId_ = other.sessionId_;
        onChanged();
      }
      if (other.getVersion() != 0) {
        setVersion(other.getVersion());
      }
      if (!other.getSign().isEmpty()) {
        sign_ = other.sign_;
        onChanged();
      }
      if (!other.getNonce().isEmpty()) {
        nonce_ = other.nonce_;
        onChanged();
      }
      if (!other.getUserAgent().isEmpty()) {
        userAgent_ = other.userAgent_;
        onChanged();
      }
      if (!other.getPath().isEmpty()) {
        path_ = other.path_;
        onChanged();
      }
      if (other.hasParam()) {
        mergeParam(other.getParam());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.argo.sdk.protobuf.PAppRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.argo.sdk.protobuf.PAppRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object authId_ = "";
    /**
     * <code>optional string authId = 1;</code>
     */
    public java.lang.String getAuthId() {
      java.lang.Object ref = authId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        authId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string authId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAuthIdBytes() {
      java.lang.Object ref = authId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        authId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string authId = 1;</code>
     */
    public Builder setAuthId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      authId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string authId = 1;</code>
     */
    public Builder clearAuthId() {
      
      authId_ = getDefaultInstance().getAuthId();
      onChanged();
      return this;
    }
    /**
     * <code>optional string authId = 1;</code>
     */
    public Builder setAuthIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      authId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object sessionId_ = "";
    /**
     * <code>optional string sessionId = 2;</code>
     */
    public java.lang.String getSessionId() {
      java.lang.Object ref = sessionId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sessionId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string sessionId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSessionIdBytes() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string sessionId = 2;</code>
     */
    public Builder setSessionId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sessionId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string sessionId = 2;</code>
     */
    public Builder clearSessionId() {
      
      sessionId_ = getDefaultInstance().getSessionId();
      onChanged();
      return this;
    }
    /**
     * <code>optional string sessionId = 2;</code>
     */
    public Builder setSessionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sessionId_ = value;
      onChanged();
      return this;
    }

    private int version_ ;
    /**
     * <code>optional int32 version = 3;</code>
     */
    public int getVersion() {
      return version_;
    }
    /**
     * <code>optional int32 version = 3;</code>
     */
    public Builder setVersion(int value) {
      
      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 version = 3;</code>
     */
    public Builder clearVersion() {
      
      version_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object sign_ = "";
    /**
     * <code>optional string sign = 4;</code>
     */
    public java.lang.String getSign() {
      java.lang.Object ref = sign_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sign_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string sign = 4;</code>
     */
    public com.google.protobuf.ByteString
        getSignBytes() {
      java.lang.Object ref = sign_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sign_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string sign = 4;</code>
     */
    public Builder setSign(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sign_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string sign = 4;</code>
     */
    public Builder clearSign() {
      
      sign_ = getDefaultInstance().getSign();
      onChanged();
      return this;
    }
    /**
     * <code>optional string sign = 4;</code>
     */
    public Builder setSignBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sign_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object nonce_ = "";
    /**
     * <code>optional string nonce = 5;</code>
     */
    public java.lang.String getNonce() {
      java.lang.Object ref = nonce_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nonce_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string nonce = 5;</code>
     */
    public com.google.protobuf.ByteString
        getNonceBytes() {
      java.lang.Object ref = nonce_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nonce_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string nonce = 5;</code>
     */
    public Builder setNonce(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      nonce_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string nonce = 5;</code>
     */
    public Builder clearNonce() {
      
      nonce_ = getDefaultInstance().getNonce();
      onChanged();
      return this;
    }
    /**
     * <code>optional string nonce = 5;</code>
     */
    public Builder setNonceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      nonce_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object userAgent_ = "";
    /**
     * <code>optional string userAgent = 6;</code>
     */
    public java.lang.String getUserAgent() {
      java.lang.Object ref = userAgent_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userAgent_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string userAgent = 6;</code>
     */
    public com.google.protobuf.ByteString
        getUserAgentBytes() {
      java.lang.Object ref = userAgent_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userAgent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string userAgent = 6;</code>
     */
    public Builder setUserAgent(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userAgent_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string userAgent = 6;</code>
     */
    public Builder clearUserAgent() {
      
      userAgent_ = getDefaultInstance().getUserAgent();
      onChanged();
      return this;
    }
    /**
     * <code>optional string userAgent = 6;</code>
     */
    public Builder setUserAgentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userAgent_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object path_ = "";
    /**
     * <code>optional string path = 7;</code>
     */
    public java.lang.String getPath() {
      java.lang.Object ref = path_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        path_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string path = 7;</code>
     */
    public com.google.protobuf.ByteString
        getPathBytes() {
      java.lang.Object ref = path_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        path_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string path = 7;</code>
     */
    public Builder setPath(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      path_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string path = 7;</code>
     */
    public Builder clearPath() {
      
      path_ = getDefaultInstance().getPath();
      onChanged();
      return this;
    }
    /**
     * <code>optional string path = 7;</code>
     */
    public Builder setPathBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      path_ = value;
      onChanged();
      return this;
    }

    private com.argo.sdk.protobuf.PAppRequestParam param_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.argo.sdk.protobuf.PAppRequestParam, com.argo.sdk.protobuf.PAppRequestParam.Builder, com.argo.sdk.protobuf.PAppRequestParamOrBuilder> paramBuilder_;
    /**
     * <code>optional .PAppRequestParam param = 8;</code>
     */
    public boolean hasParam() {
      return paramBuilder_ != null || param_ != null;
    }
    /**
     * <code>optional .PAppRequestParam param = 8;</code>
     */
    public com.argo.sdk.protobuf.PAppRequestParam getParam() {
      if (paramBuilder_ == null) {
        return param_ == null ? com.argo.sdk.protobuf.PAppRequestParam.getDefaultInstance() : param_;
      } else {
        return paramBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .PAppRequestParam param = 8;</code>
     */
    public Builder setParam(com.argo.sdk.protobuf.PAppRequestParam value) {
      if (paramBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        param_ = value;
        onChanged();
      } else {
        paramBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .PAppRequestParam param = 8;</code>
     */
    public Builder setParam(
        com.argo.sdk.protobuf.PAppRequestParam.Builder builderForValue) {
      if (paramBuilder_ == null) {
        param_ = builderForValue.build();
        onChanged();
      } else {
        paramBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .PAppRequestParam param = 8;</code>
     */
    public Builder mergeParam(com.argo.sdk.protobuf.PAppRequestParam value) {
      if (paramBuilder_ == null) {
        if (param_ != null) {
          param_ =
            com.argo.sdk.protobuf.PAppRequestParam.newBuilder(param_).mergeFrom(value).buildPartial();
        } else {
          param_ = value;
        }
        onChanged();
      } else {
        paramBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .PAppRequestParam param = 8;</code>
     */
    public Builder clearParam() {
      if (paramBuilder_ == null) {
        param_ = null;
        onChanged();
      } else {
        param_ = null;
        paramBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .PAppRequestParam param = 8;</code>
     */
    public com.argo.sdk.protobuf.PAppRequestParam.Builder getParamBuilder() {
      
      onChanged();
      return getParamFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .PAppRequestParam param = 8;</code>
     */
    public com.argo.sdk.protobuf.PAppRequestParamOrBuilder getParamOrBuilder() {
      if (paramBuilder_ != null) {
        return paramBuilder_.getMessageOrBuilder();
      } else {
        return param_ == null ?
            com.argo.sdk.protobuf.PAppRequestParam.getDefaultInstance() : param_;
      }
    }
    /**
     * <code>optional .PAppRequestParam param = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.argo.sdk.protobuf.PAppRequestParam, com.argo.sdk.protobuf.PAppRequestParam.Builder, com.argo.sdk.protobuf.PAppRequestParamOrBuilder> 
        getParamFieldBuilder() {
      if (paramBuilder_ == null) {
        paramBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.argo.sdk.protobuf.PAppRequestParam, com.argo.sdk.protobuf.PAppRequestParam.Builder, com.argo.sdk.protobuf.PAppRequestParamOrBuilder>(
                getParam(),
                getParentForChildren(),
                isClean());
        param_ = null;
      }
      return paramBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:PAppRequest)
  }

  // @@protoc_insertion_point(class_scope:PAppRequest)
  private static final com.argo.sdk.protobuf.PAppRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.argo.sdk.protobuf.PAppRequest();
  }

  public static com.argo.sdk.protobuf.PAppRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PAppRequest>
      PARSER = new com.google.protobuf.AbstractParser<PAppRequest>() {
    public PAppRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new PAppRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PAppRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PAppRequest> getParserForType() {
    return PARSER;
  }

  public com.argo.sdk.protobuf.PAppRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

