// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PAppResponse.proto

package com.argo.web.protobuf;

public interface PAppResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PAppResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string msg = 1;</code>
   */
  boolean hasMsg();
  /**
   * <code>optional string msg = 1;</code>
   */
  java.lang.String getMsg();
  /**
   * <code>optional string msg = 1;</code>
   */
  com.google.protobuf.ByteString
      getMsgBytes();

  /**
   * <code>optional string sessionId = 2;</code>
   */
  boolean hasSessionId();
  /**
   * <code>optional string sessionId = 2;</code>
   */
  java.lang.String getSessionId();
  /**
   * <code>optional string sessionId = 2;</code>
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();

  /**
   * <code>optional int32 version = 3;</code>
   */
  boolean hasVersion();
  /**
   * <code>optional int32 version = 3;</code>
   */
  int getVersion();

  /**
   * <code>required int32 code = 4;</code>
   */
  boolean hasCode();
  /**
   * <code>required int32 code = 4;</code>
   */
  int getCode();

  /**
   * <code>optional int32 total = 5;</code>
   */
  boolean hasTotal();
  /**
   * <code>optional int32 total = 5;</code>
   */
  int getTotal();

  /**
   * <code>repeated bytes data = 6;</code>
   */
  java.util.List<com.google.protobuf.ByteString> getDataList();
  /**
   * <code>repeated bytes data = 6;</code>
   */
  int getDataCount();
  /**
   * <code>repeated bytes data = 6;</code>
   */
  com.google.protobuf.ByteString getData(int index);

  /**
   * <code>repeated string errors = 7;</code>
   */
  java.util.List<java.lang.String>
      getErrorsList();
  /**
   * <code>repeated string errors = 7;</code>
   */
  int getErrorsCount();
  /**
   * <code>repeated string errors = 7;</code>
   */
  java.lang.String getErrors(int index);
  /**
   * <code>repeated string errors = 7;</code>
   */
  com.google.protobuf.ByteString
      getErrorsBytes(int index);
}
