// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PAppRequest.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30001
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class PAppRequestParam;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - PappRequestRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface PappRequestRoot : GPBRootObject
@end

#pragma mark - PAppRequestParam

typedef GPB_ENUM(PAppRequestParam_FieldNumber) {
  PAppRequestParam_FieldNumber_Name = 1,
  PAppRequestParam_FieldNumber_IntValue = 2,
  PAppRequestParam_FieldNumber_StrValue = 3,
  PAppRequestParam_FieldNumber_LongValue = 4,
  PAppRequestParam_FieldNumber_FloatValue = 5,
  PAppRequestParam_FieldNumber_BoolValue = 6,
  PAppRequestParam_FieldNumber_BytesValue = 7,
};

@interface PAppRequestParam : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite) int32_t intValue;

@property(nonatomic, readwrite, copy, null_resettable) NSString *strValue;

@property(nonatomic, readwrite) int64_t longValue;

@property(nonatomic, readwrite) float floatValue;

@property(nonatomic, readwrite) BOOL boolValue;

@property(nonatomic, readwrite, copy, null_resettable) NSData *bytesValue;

@end

#pragma mark - PAppRequest

typedef GPB_ENUM(PAppRequest_FieldNumber) {
  PAppRequest_FieldNumber_AuthId = 1,
  PAppRequest_FieldNumber_SessionId = 2,
  PAppRequest_FieldNumber_Version = 3,
  PAppRequest_FieldNumber_Sign = 4,
  PAppRequest_FieldNumber_Nonce = 5,
  PAppRequest_FieldNumber_UserAgent = 6,
  PAppRequest_FieldNumber_Path = 7,
  PAppRequest_FieldNumber_Param = 8,
};

@interface PAppRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *authId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *sessionId;

@property(nonatomic, readwrite) int32_t version;

@property(nonatomic, readwrite, copy, null_resettable) NSString *sign;

@property(nonatomic, readwrite, copy, null_resettable) NSString *nonce;

@property(nonatomic, readwrite, copy, null_resettable) NSString *userAgent;

@property(nonatomic, readwrite, copy, null_resettable) NSString *path;

@property(nonatomic, readwrite, strong, null_resettable) PAppRequestParam *param;
/** Test to see if @c param has been set. */
@property(nonatomic, readwrite) BOOL hasParam;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
