// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PAppSession.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30001
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - PappSessionRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface PappSessionRoot : GPBRootObject
@end

#pragma mark - PAppSession

typedef GPB_ENUM(PAppSession_FieldNumber) {
  PAppSession_FieldNumber_SessionId = 1,
  PAppSession_FieldNumber_RealName = 2,
  PAppSession_FieldNumber_UserName = 3,
  PAppSession_FieldNumber_UserId = 4,
  PAppSession_FieldNumber_Secret = 5,
  PAppSession_FieldNumber_SigninDate = 6,
  PAppSession_FieldNumber_ProfileImageURL = 7,
  PAppSession_FieldNumber_AppName = 8,
  PAppSession_FieldNumber_DeviceName = 9,
  PAppSession_FieldNumber_DeviceScreenSize = 10,
  PAppSession_FieldNumber_OsName = 11,
  PAppSession_FieldNumber_OsVersion = 12,
  PAppSession_FieldNumber_PackageVersion = 13,
  PAppSession_FieldNumber_PackageName = 14,
  PAppSession_FieldNumber_DeviceId = 15,
  PAppSession_FieldNumber_DeviceToken = 16,
  PAppSession_FieldNumber_ApnsEnabled = 17,
  PAppSession_FieldNumber_LatesAppVers = 18,
  PAppSession_FieldNumber_LocaleIdentifier = 19,
  PAppSession_FieldNumber_Latitude = 20,
  PAppSession_FieldNumber_Longitude = 21,
  PAppSession_FieldNumber_CityId = 22,
  PAppSession_FieldNumber_UserKind = 23,
  PAppSession_FieldNumber_UserDemo = 24,
};

@interface PAppSession : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *sessionId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *realName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *userName;

@property(nonatomic, readwrite) int64_t userId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *secret;

@property(nonatomic, readwrite, copy, null_resettable) NSString *signinDate;

@property(nonatomic, readwrite, copy, null_resettable) NSString *profileImageURL;

@property(nonatomic, readwrite, copy, null_resettable) NSString *appName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceScreenSize;

@property(nonatomic, readwrite, copy, null_resettable) NSString *osName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *osVersion;

@property(nonatomic, readwrite, copy, null_resettable) NSString *packageVersion;

@property(nonatomic, readwrite, copy, null_resettable) NSString *packageName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceToken;

@property(nonatomic, readwrite) int32_t apnsEnabled;

@property(nonatomic, readwrite, copy, null_resettable) NSString *latesAppVers;

@property(nonatomic, readwrite, copy, null_resettable) NSString *localeIdentifier;

@property(nonatomic, readwrite) float latitude;

@property(nonatomic, readwrite) float longitude;

@property(nonatomic, readwrite) int32_t cityId;

@property(nonatomic, readwrite) int32_t userKind;

@property(nonatomic, readwrite) int32_t userDemo;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
