// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PAppResponse.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30001
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - PappResponseRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface PappResponseRoot : GPBRootObject
@end

#pragma mark - PAppResponse

typedef GPB_ENUM(PAppResponse_FieldNumber) {
  PAppResponse_FieldNumber_Msg = 1,
  PAppResponse_FieldNumber_SessionId = 2,
  PAppResponse_FieldNumber_Version = 3,
  PAppResponse_FieldNumber_Code = 4,
  PAppResponse_FieldNumber_Total = 5,
  PAppResponse_FieldNumber_DataArray = 6,
  PAppResponse_FieldNumber_ErrorsArray = 7,
};

@interface PAppResponse : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *msg;

@property(nonatomic, readwrite, copy, null_resettable) NSString *sessionId;

@property(nonatomic, readwrite) int32_t version;

@property(nonatomic, readwrite) int32_t code;

@property(nonatomic, readwrite) int32_t total;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSData*> *dataArray;
/** The number of items in @c dataArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger dataArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *errorsArray;
/** The number of items in @c errorsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger errorsArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
