// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PAppSession.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "PappSession.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - PappSessionRoot

@implementation PappSessionRoot

@end

#pragma mark - PappSessionRoot_FileDescriptor

static GPBFileDescriptor *PappSessionRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@""
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - PAppSession

@implementation PAppSession

@dynamic sessionId;
@dynamic realName;
@dynamic userName;
@dynamic userId;
@dynamic secret;
@dynamic signinDate;
@dynamic profileImageURL;
@dynamic appName;
@dynamic deviceName;
@dynamic deviceScreenSize;
@dynamic osName;
@dynamic osVersion;
@dynamic packageVersion;
@dynamic packageName;
@dynamic deviceId;
@dynamic deviceToken;
@dynamic apnsEnabled;
@dynamic latesAppVers;
@dynamic localeIdentifier;
@dynamic latitude;
@dynamic longitude;
@dynamic cityId;
@dynamic userKind;
@dynamic userDemo;

typedef struct PAppSession__storage_ {
  uint32_t _has_storage_[1];
  int32_t apnsEnabled;
  float latitude;
  float longitude;
  int32_t cityId;
  int32_t userKind;
  int32_t userDemo;
  NSString *sessionId;
  NSString *realName;
  NSString *userName;
  NSString *secret;
  NSString *signinDate;
  NSString *profileImageURL;
  NSString *appName;
  NSString *deviceName;
  NSString *deviceScreenSize;
  NSString *osName;
  NSString *osVersion;
  NSString *packageVersion;
  NSString *packageName;
  NSString *deviceId;
  NSString *deviceToken;
  NSString *latesAppVers;
  NSString *localeIdentifier;
  int64_t userId;
} PAppSession__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "sessionId",
        .dataTypeSpecific.className = NULL,
        .number = PAppSession_FieldNumber_SessionId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(PAppSession__storage_, sessionId),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "realName",
        .dataTypeSpecific.className = NULL,
        .number = PAppSession_FieldNumber_RealName,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(PAppSession__storage_, realName),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "userName",
        .dataTypeSpecific.className = NULL,
        .number = PAppSession_FieldNumber_UserName,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(PAppSession__storage_, userName),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "userId",
        .dataTypeSpecific.className = NULL,
        .number = PAppSession_FieldNumber_UserId,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(PAppSession__storage_, userId),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "secret",
        .dataTypeSpecific.className = NULL,
        .number = PAppSession_FieldNumber_Secret,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(PAppSession__storage_, secret),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "signinDate",
        .dataTypeSpecific.className = NULL,
        .number = PAppSession_FieldNumber_SigninDate,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(PAppSession__storage_, signinDate),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "profileImageURL",
        .dataTypeSpecific.className = NULL,
        .number = PAppSession_FieldNumber_ProfileImageURL,
        .hasIndex = 6,
        .offset = (uint32_t)offsetof(PAppSession__storage_, profileImageURL),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "appName",
        .dataTypeSpecific.className = NULL,
        .number = PAppSession_FieldNumber_AppName,
        .hasIndex = 7,
        .offset = (uint32_t)offsetof(PAppSession__storage_, appName),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "deviceName",
        .dataTypeSpecific.className = NULL,
        .number = PAppSession_FieldNumber_DeviceName,
        .hasIndex = 8,
        .offset = (uint32_t)offsetof(PAppSession__storage_, deviceName),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "deviceScreenSize",
        .dataTypeSpecific.className = NULL,
        .number = PAppSession_FieldNumber_DeviceScreenSize,
        .hasIndex = 9,
        .offset = (uint32_t)offsetof(PAppSession__storage_, deviceScreenSize),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "osName",
        .dataTypeSpecific.className = NULL,
        .number = PAppSession_FieldNumber_OsName,
        .hasIndex = 10,
        .offset = (uint32_t)offsetof(PAppSession__storage_, osName),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "osVersion",
        .dataTypeSpecific.className = NULL,
        .number = PAppSession_FieldNumber_OsVersion,
        .hasIndex = 11,
        .offset = (uint32_t)offsetof(PAppSession__storage_, osVersion),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "packageVersion",
        .dataTypeSpecific.className = NULL,
        .number = PAppSession_FieldNumber_PackageVersion,
        .hasIndex = 12,
        .offset = (uint32_t)offsetof(PAppSession__storage_, packageVersion),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "packageName",
        .dataTypeSpecific.className = NULL,
        .number = PAppSession_FieldNumber_PackageName,
        .hasIndex = 13,
        .offset = (uint32_t)offsetof(PAppSession__storage_, packageName),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "deviceId",
        .dataTypeSpecific.className = NULL,
        .number = PAppSession_FieldNumber_DeviceId,
        .hasIndex = 14,
        .offset = (uint32_t)offsetof(PAppSession__storage_, deviceId),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "deviceToken",
        .dataTypeSpecific.className = NULL,
        .number = PAppSession_FieldNumber_DeviceToken,
        .hasIndex = 15,
        .offset = (uint32_t)offsetof(PAppSession__storage_, deviceToken),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "apnsEnabled",
        .dataTypeSpecific.className = NULL,
        .number = PAppSession_FieldNumber_ApnsEnabled,
        .hasIndex = 16,
        .offset = (uint32_t)offsetof(PAppSession__storage_, apnsEnabled),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "latesAppVers",
        .dataTypeSpecific.className = NULL,
        .number = PAppSession_FieldNumber_LatesAppVers,
        .hasIndex = 17,
        .offset = (uint32_t)offsetof(PAppSession__storage_, latesAppVers),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "localeIdentifier",
        .dataTypeSpecific.className = NULL,
        .number = PAppSession_FieldNumber_LocaleIdentifier,
        .hasIndex = 18,
        .offset = (uint32_t)offsetof(PAppSession__storage_, localeIdentifier),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "latitude",
        .dataTypeSpecific.className = NULL,
        .number = PAppSession_FieldNumber_Latitude,
        .hasIndex = 19,
        .offset = (uint32_t)offsetof(PAppSession__storage_, latitude),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeFloat,
      },
      {
        .name = "longitude",
        .dataTypeSpecific.className = NULL,
        .number = PAppSession_FieldNumber_Longitude,
        .hasIndex = 20,
        .offset = (uint32_t)offsetof(PAppSession__storage_, longitude),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeFloat,
      },
      {
        .name = "cityId",
        .dataTypeSpecific.className = NULL,
        .number = PAppSession_FieldNumber_CityId,
        .hasIndex = 21,
        .offset = (uint32_t)offsetof(PAppSession__storage_, cityId),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "userKind",
        .dataTypeSpecific.className = NULL,
        .number = PAppSession_FieldNumber_UserKind,
        .hasIndex = 22,
        .offset = (uint32_t)offsetof(PAppSession__storage_, userKind),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "userDemo",
        .dataTypeSpecific.className = NULL,
        .number = PAppSession_FieldNumber_UserDemo,
        .hasIndex = 23,
        .offset = (uint32_t)offsetof(PAppSession__storage_, userDemo),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt32,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PAppSession class]
                                     rootClass:[PappSessionRoot class]
                                          file:PappSessionRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PAppSession__storage_)
                                         flags:0];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\025\001\t\000\002\010\000\003\010\000\004\006\000\006\n\000\007\r!!\000\010\007\000\t\n\000\n\020\000\013\006\000\014\t\000\r\016\000\016"
        "\013\000\017\010\000\020\013\000\021\013\000\022\014\000\023\020\000\026\006\000\027\010\000\030\010\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
