// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PAppRequest.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30001
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class PAppRequestParam;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - PappRequestRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface PappRequestRoot : GPBRootObject
@end

#pragma mark - PAppRequestParam

typedef GPB_ENUM(PAppRequestParam_FieldNumber) {
  PAppRequestParam_FieldNumber_Name = 1,
  PAppRequestParam_FieldNumber_IntValue = 2,
  PAppRequestParam_FieldNumber_StrValue = 3,
  PAppRequestParam_FieldNumber_LongValue = 4,
  PAppRequestParam_FieldNumber_FloatValue = 5,
  PAppRequestParam_FieldNumber_BoolValue = 6,
  PAppRequestParam_FieldNumber_BytesValue = 7,
};

@interface PAppRequestParam : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;
/** Test to see if @c name has been set. */
@property(nonatomic, readwrite) BOOL hasName;

@property(nonatomic, readwrite) int32_t intValue;

@property(nonatomic, readwrite) BOOL hasIntValue;
@property(nonatomic, readwrite, copy, null_resettable) NSString *strValue;
/** Test to see if @c strValue has been set. */
@property(nonatomic, readwrite) BOOL hasStrValue;

@property(nonatomic, readwrite) int64_t longValue;

@property(nonatomic, readwrite) BOOL hasLongValue;
@property(nonatomic, readwrite) float floatValue;

@property(nonatomic, readwrite) BOOL hasFloatValue;
@property(nonatomic, readwrite) BOOL boolValue;

@property(nonatomic, readwrite) BOOL hasBoolValue;
@property(nonatomic, readwrite, copy, null_resettable) NSData *bytesValue;
/** Test to see if @c bytesValue has been set. */
@property(nonatomic, readwrite) BOOL hasBytesValue;

@end

#pragma mark - PAppRequest

typedef GPB_ENUM(PAppRequest_FieldNumber) {
  PAppRequest_FieldNumber_AuthId = 1,
  PAppRequest_FieldNumber_SessionId = 2,
  PAppRequest_FieldNumber_Version = 3,
  PAppRequest_FieldNumber_Sign = 4,
  PAppRequest_FieldNumber_Nonce = 5,
  PAppRequest_FieldNumber_UserAgent = 6,
  PAppRequest_FieldNumber_Path = 7,
  PAppRequest_FieldNumber_ParamArray = 8,
};

@interface PAppRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *authId;
/** Test to see if @c authId has been set. */
@property(nonatomic, readwrite) BOOL hasAuthId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *sessionId;
/** Test to see if @c sessionId has been set. */
@property(nonatomic, readwrite) BOOL hasSessionId;

@property(nonatomic, readwrite) int32_t version;

@property(nonatomic, readwrite) BOOL hasVersion;
@property(nonatomic, readwrite, copy, null_resettable) NSString *sign;
/** Test to see if @c sign has been set. */
@property(nonatomic, readwrite) BOOL hasSign;

@property(nonatomic, readwrite, copy, null_resettable) NSString *nonce;
/** Test to see if @c nonce has been set. */
@property(nonatomic, readwrite) BOOL hasNonce;

@property(nonatomic, readwrite, copy, null_resettable) NSString *userAgent;
/** Test to see if @c userAgent has been set. */
@property(nonatomic, readwrite) BOOL hasUserAgent;

@property(nonatomic, readwrite, copy, null_resettable) NSString *path;
/** Test to see if @c path has been set. */
@property(nonatomic, readwrite) BOOL hasPath;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<PAppRequestParam*> *paramArray;
/** The number of items in @c paramArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger paramArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
